import { ADMIN_APP as BASE_ADMIN_APP } from './admin-v17';

const GALLERY_CSS = String.raw`
.section.stageBefore,.section.stageAfter{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:24px 0 0!important;padding:13px 14px 12px!important;border-radius:18px 18px 0 0;font-size:19px!important;letter-spacing:.2px}
.section.stageBefore{background:linear-gradient(135deg,#32260d,#1c170d);border:1px solid #8a671b;border-bottom:0;color:#ffd56b}
.section.stageAfter{background:linear-gradient(135deg,#123322,#101f18);border:1px solid #286c48;border-bottom:0;color:#8be3ad}
.stageTitle{display:flex;align-items:center;gap:9px;font-weight:950}.stageDot{width:10px;height:10px;border-radius:50%;box-shadow:0 0 14px currentColor;background:currentColor}.stageCount{font-size:12px;font-weight:900;padding:7px 10px;border-radius:999px;white-space:nowrap}.stageBefore .stageCount{background:#5b4313;color:#ffe39a}.stageAfter .stageCount{background:#174b31;color:#a9efc1}
.gallery.stageGallery{padding:12px;border-width:1px;border-style:solid;border-top:0;border-radius:0 0 18px 18px;margin:0 0 8px;position:relative}.gallery.stageGallery.before{background:linear-gradient(180deg,#17130a,#101112);border-color:#8a671b}.gallery.stageGallery.after{background:linear-gradient(180deg,#0e1d16,#101112);border-color:#286c48}
.gallery.stageGallery .empty{grid-column:1/-1;padding:24px 10px}.gallery.stageGallery .media{position:relative;cursor:pointer;transition:transform .16s ease,border-color .16s ease;isolation:isolate}.gallery.stageGallery .media:active{transform:scale(.985)}.gallery.stageGallery.before .media{border-color:#71571f}.gallery.stageGallery.after .media{border-color:#245e41}
.gallery.stageGallery .media:before{content:attr(data-stage-label);position:absolute;left:8px;top:8px;z-index:4;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:950;letter-spacing:.6px;backdrop-filter:blur(7px)}.gallery.stageGallery.before .media:before{background:#4a350fd9;color:#ffdb78;border:1px solid #9a7121}.gallery.stageGallery.after .media:before{background:#143e2ad9;color:#9cebbb;border:1px solid #2d7951}
.gallery.stageGallery .media:after{content:'↗';position:absolute;right:8px;top:8px;z-index:4;width:28px;height:28px;display:grid;place-items:center;border-radius:50%;background:#090b0dcc;border:1px solid #59616b;color:#fff;font-size:14px}.gallery.stageGallery .media img,.gallery.stageGallery .media video{pointer-events:none}
#hcViewer{position:fixed;inset:0;z-index:9999;background:rgba(3,5,7,.97);display:none;flex-direction:column;touch-action:pan-y;backdrop-filter:blur(18px);padding:calc(12px + env(safe-area-inset-top)) 12px calc(14px + env(safe-area-inset-bottom))}#hcViewer.on{display:flex}.viewerTop{display:grid;grid-template-columns:54px 1fr 54px;align-items:center;min-height:50px}.viewerClose{width:44px;height:44px;border-radius:50%;border:1px solid #444d57;background:#11171d;color:#fff;font-size:25px}.viewerStage{text-align:center;font-size:13px;font-weight:950;letter-spacing:.8px}.viewerStage.before{color:#ffd260}.viewerStage.after{color:#8ce5ae}.viewerCounter{text-align:right;color:#b2bbc6;font-size:13px;font-weight:850}.viewerBody{position:relative;flex:1;min-height:0;display:grid;place-items:center;overflow:hidden}.viewerMedia{max-width:100%;max-height:100%;display:grid;place-items:center}.viewerBody img,.viewerBody video{max-width:100%;max-height:100%;width:auto;height:auto;object-fit:contain;border-radius:12px;background:#000;box-shadow:0 12px 40px #0008}.viewerBody video{width:100%;max-height:82vh}.viewerArrow{position:absolute;top:50%;transform:translateY(-50%);width:46px;height:54px;border-radius:14px;border:1px solid #46505b;background:#0c1117d9;color:white;font-size:28px;z-index:5}.viewerPrev{left:2px}.viewerNext{right:2px}.viewerHint{text-align:center;color:#78838f;font-size:11px;padding-top:9px}
@media(max-width:430px){.section.stageBefore,.section.stageAfter{font-size:18px!important}.gallery.stageGallery{gap:8px;padding:9px}.viewerArrow{width:40px;height:50px}.viewerTop{grid-template-columns:48px 1fr 48px}}
`;

const GALLERY_SCRIPT = String.raw`
<script>(function(){
var viewer=null,viewerItems=[],viewerIndex=0,viewerStage='before',touchX=0;
function q(id){return document.getElementById(id)}
function ensureViewer(){if(viewer)return viewer;viewer=document.createElement('div');viewer.id='hcViewer';viewer.innerHTML='<div class="viewerTop"><button class="viewerClose" aria-label="Закрыть">×</button><div class="viewerStage"></div><div class="viewerCounter"></div></div><div class="viewerBody"><button class="viewerArrow viewerPrev" aria-label="Предыдущее">‹</button><div class="viewerMedia"></div><button class="viewerArrow viewerNext" aria-label="Следующее">›</button></div><div class="viewerHint">Смахните влево или вправо, чтобы листать</div>';document.body.appendChild(viewer);viewer.querySelector('.viewerClose').onclick=closeViewer;viewer.querySelector('.viewerPrev').onclick=function(){move(-1)};viewer.querySelector('.viewerNext').onclick=function(){move(1)};viewer.addEventListener('touchstart',function(e){touchX=e.changedTouches&&e.changedTouches[0]?e.changedTouches[0].clientX:0},{passive:true});viewer.addEventListener('touchend',function(e){var x=e.changedTouches&&e.changedTouches[0]?e.changedTouches[0].clientX:touchX,d=x-touchX;if(Math.abs(d)>45)move(d<0?1:-1)},{passive:true});document.addEventListener('keydown',function(e){if(!viewer.classList.contains('on'))return;if(e.key==='Escape')closeViewer();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});return viewer}
function collect(stage){var box=q(stage==='before'?'beforeGallery':'afterGallery');if(!box)return[];return Array.prototype.slice.call(box.querySelectorAll('.media')).map(function(el){var node=el.querySelector('img,video');if(!node||!node.src)return null;return{type:node.tagName==='VIDEO'?'video':'photo',src:node.src,el:el}}).filter(Boolean)}
function openViewer(stage,el){ensureViewer();viewerStage=stage;viewerItems=collect(stage);viewerIndex=Math.max(0,viewerItems.findIndex(function(x){return x.el===el}));if(!viewerItems.length)return;renderViewer();viewer.classList.add('on');document.body.style.overflow='hidden'}
function closeViewer(){if(!viewer)return;var v=viewer.querySelector('video');if(v)try{v.pause()}catch(e){}viewer.classList.remove('on');viewer.querySelector('.viewerMedia').innerHTML='';document.body.style.overflow=''}
function move(d){if(!viewerItems.length)return;viewerIndex=(viewerIndex+d+viewerItems.length)%viewerItems.length;renderViewer()}
function renderViewer(){var item=viewerItems[viewerIndex],host=viewer.querySelector('.viewerMedia'),stageEl=viewer.querySelector('.viewerStage');host.innerHTML=item.type==='video'?'<video src="'+item.src+'" controls autoplay playsinline></video>':'<img src="'+item.src+'" alt="Фото объекта">';stageEl.textContent=viewerStage==='before'?'ДО УБОРКИ':'ПОСЛЕ УБОРКИ';stageEl.className='viewerStage '+viewerStage;viewer.querySelector('.viewerCounter').textContent=(viewerIndex+1)+' / '+viewerItems.length;viewer.querySelector('.viewerPrev').style.display=viewerItems.length>1?'block':'none';viewer.querySelector('.viewerNext').style.display=viewerItems.length>1?'block':'none'}
function word(n){return n===1?'файл':(n>=2&&n<=4?'файла':'файлов')}
function decorateStage(stage){var box=q(stage==='before'?'beforeGallery':'afterGallery');if(!box)return;box.classList.add('stageGallery',stage);var heading=box.previousElementSibling;if(heading&&heading.classList.contains('section')){heading.classList.add(stage==='before'?'stageBefore':'stageAfter');var count=box.querySelectorAll('.media').length;heading.innerHTML='<span class="stageTitle"><i class="stageDot"></i>'+(stage==='before'?'ДО УБОРКИ':'ПОСЛЕ УБОРКИ')+'</span><span class="stageCount">'+count+' '+word(count)+'</span>'}Array.prototype.forEach.call(box.querySelectorAll('.media'),function(el){el.setAttribute('data-stage-label',stage==='before'?'ДО':'ПОСЛЕ');if(el.dataset.viewerBound)return;el.dataset.viewerBound='1';el.addEventListener('click',function(){if(el.querySelector('img,video'))openViewer(stage,el)});var vid=el.querySelector('video');if(vid){vid.removeAttribute('controls');vid.muted=true;vid.playsInline=true}})}
function decorate(){decorateStage('before');decorateStage('after')}
var scheduled=false;function queue(){if(scheduled)return;scheduled=true;requestAnimationFrame(function(){scheduled=false;decorate()})}new MutationObserver(queue).observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('load',function(){setTimeout(decorate,120)})
})();</script>`;

export const ADMIN_APP = BASE_ADMIN_APP.replace('</style>',GALLERY_CSS+'</style>').replace('</body></html>',GALLERY_SCRIPT+'</body></html>');
