import { APP as BASE_APP } from './app-v18-fast';

const PREMIUM_CSS = String.raw`
:root{--pbg:#070a0d;--ppanel:#121920;--ppanel2:#171f27;--pline:#303b47;--pgold:#f5bd45;--pgold2:#dfa329;--pmuted:#97a3b3}
html,body{background:#070a0d!important}
body{padding-bottom:calc(92px + env(safe-area-inset-bottom))!important}
.app{max-width:760px!important;padding:0 16px 28px!important}
.brand{position:relative;min-height:138px;margin:0 -16px 12px!important;padding:22px 20px 56px!important;justify-content:flex-start!important;overflow:hidden;background:linear-gradient(180deg,rgba(4,7,10,.08),rgba(7,10,13,.98)),url("https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=55") center 45%/cover no-repeat}
.brand:after{content:"";position:absolute;left:0;right:0;bottom:0;height:74px;background:linear-gradient(180deg,transparent,#070a0d);pointer-events:none}
.mark{position:relative;z-index:2;width:58px!important;height:52px!important;border:0!important;border-radius:0!important;background:transparent!important;color:var(--pgold)!important;font-size:30px!important;font-weight:950!important;letter-spacing:-5px!important}
.brandText{position:relative;z-index:2}.brandText b{color:var(--pgold)!important;font-family:Georgia,serif!important;font-size:21px!important;letter-spacing:.6px!important}.brandText span{color:#d7a53a!important;font-size:8px!important;letter-spacing:2.7px!important;margin-top:4px!important}
.hero{position:relative;background:transparent!important;border:0!important;border-radius:0!important;padding:0 0 6px!important;margin:-28px 0 6px!important}
.hero .premiumProgress{display:flex;align-items:center;gap:12px;margin:0 0 26px}.premiumProgress .pStep{color:#a8b3c2;font-size:14px;white-space:nowrap}.premiumProgress .pBars{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;flex:1}.premiumProgress i{height:7px;border-radius:99px;background:#252e37}.premiumProgress i.on{background:linear-gradient(90deg,#ffd167,#dda127);box-shadow:0 0 12px #dca02640}
.heroTop{align-items:flex-start!important}.hero h1{font-size:42px!important;line-height:1!important;letter-spacing:-1.5px!important;margin:0 0 11px!important}.hero p{font-size:19px!important;line-height:1.35!important;color:var(--pmuted)!important}.pill{display:none!important}.who{display:none!important}
.sectionTitle{font-size:38px!important;line-height:1!important;letter-spacing:-1.2px!important;margin:20px 2px 9px!important}.sectionSub{font-size:17px!important;color:var(--pmuted)!important;margin-bottom:20px!important}
.card{border-color:var(--pline)!important;background:linear-gradient(145deg,#151d24,#10161b)!important;box-shadow:inset 0 1px 0 #ffffff08!important}
#content .card:has(#customer){border:0!important;background:transparent!important;box-shadow:none!important;padding:0!important;margin:0!important}
#content .card:has(#customer) .field{position:relative;margin:14px 0!important;padding:16px 16px 16px 72px;border:1px solid var(--pline);border-radius:21px;background:linear-gradient(145deg,#151d24,#10161b);min-height:104px;display:flex;flex-direction:column;justify-content:center}
#content .card:has(#customer) .field:before{position:absolute;left:22px;top:50%;transform:translateY(-50%);color:var(--pgold);font-size:30px;font-weight:800}
#content .card:has(#customer) .field:nth-child(1):before{content:"●"}#content .card:has(#customer) .field:nth-child(2):before{content:"⌖"}#content .card:has(#customer) .field:nth-child(3):before{content:"☷"}
.label{font-size:15px!important;margin-bottom:7px!important}
input,select,textarea{border-color:#35414d!important;background:#0d1318!important;border-radius:14px!important;padding:14px 15px!important;font-size:18px!important}
input:focus,select:focus,textarea:focus{border-color:#a88031!important;box-shadow:0 0 0 3px #f5bd4517!important}
.confirm{border-color:var(--pline)!important;background:linear-gradient(145deg,#151d24,#10161b)!important;border-radius:20px!important;padding:17px!important;gap:15px!important}.confirm input{width:48px!important;height:48px!important;min-width:48px!important;border-radius:13px!important}.confirm span{font-size:17px!important}
.hint{border-color:var(--pline)!important;background:linear-gradient(145deg,#141b22,#10161b)!important;border-radius:18px!important;padding:16px 18px!important;color:#9ca9b9!important}.hint strong{color:#d6dde6!important}
.primary{border-radius:18px!important;padding:18px 20px!important;background:linear-gradient(135deg,#ffd36a,#dfa228)!important;color:#0b0e11!important;font-size:20px!important;box-shadow:0 10px 28px #d99d2430!important}.secondary{border-color:#44515f!important;background:#111820!important;border-radius:16px!important}
.steps{margin:4px 0 17px!important}.step{font-size:11px!important}.step.on i{background:var(--pgold)!important;border-color:var(--pgold)!important}
.media{border-color:var(--pline)!important;background:#10161b!important;border-radius:20px!important}.addMedia{min-height:150px!important;border-color:#916e22!important;border-radius:18px!important;background:linear-gradient(145deg,#171b17,#11150f)!important;font-size:20px!important}.addMedia:before{content:"＋";display:block;width:58px;height:58px;border-radius:50%;margin:0 auto 10px;background:#272315;color:#ffd166;font-size:39px;line-height:56px}.addMedia small{color:#aaa083!important}
.file{border-color:var(--pline)!important;background:#141b22!important;border-radius:14px!important}.fileIcon{background:#242119!important;color:var(--pgold)!important}.waitOrb{border-color:#8d6b20!important;background:radial-gradient(circle,#3b2f12,#16140f 70%)!important}.timer{font-size:50px!important}.reg div{border-color:var(--pline)!important;background:#121920!important}
.request{border-color:var(--pline)!important;background:linear-gradient(145deg,#151d24,#10161b)!important;border-radius:21px!important;padding:17px!important;margin:12px 0!important}.requestTop b{font-size:22px!important}.tag{background:linear-gradient(135deg,#ffd36a,#dfa228)!important;color:#111!important;border-radius:999px!important;padding:8px 11px!important}.tag.done{background:#194b2b!important;color:#8ee2a0!important}.requestMeta{font-size:15px!important;gap:7px!important}.request .primary{margin-top:14px!important}
.profileHead{border-color:var(--pline)!important;background:linear-gradient(145deg,#151d24,#10161b)!important;border-radius:22px!important;padding:20px!important}.avatar{width:76px!important;height:76px!important;background:linear-gradient(145deg,#f7c757,#d99a23)!important;color:#111!important}.profileHead h2{font-size:28px!important}.profileHead p{font-size:14px!important}
.menuBtn{border-color:var(--pline)!important;background:linear-gradient(145deg,#151d24,#10161b)!important;border-radius:20px!important;padding:16px!important;margin-top:12px!important}.menuBtn i{width:52px!important;height:52px!important;border-radius:15px!important;background:#18212a!important;color:var(--pgold)!important}.menuBtn b{font-size:19px!important}.menuBtn small{font-size:14px!important;color:var(--pmuted)!important}.menuBtn em{font-size:30px!important;color:#9ba7b7!important}
.nav{background:#0a0f14f2!important;border-top-color:#27313b!important;padding-top:7px!important}.navBtn{color:#8c98a8!important;font-size:12px!important;padding:7px 4px!important}.navBtn i{font-size:23px!important}.navBtn.on{color:var(--pgold)!important}.navBtn.on:after{content:"";display:block;width:46px;height:3px;border-radius:99px;background:var(--pgold);margin:5px auto 0}.toast{background:#2a2110!important;border-color:#6b5220!important;color:#f8d77e!important}.overlay{backdrop-filter:blur(8px)!important;background:#06090cdb!important}
body.keyboard-open .brand{min-height:84px;padding-bottom:16px!important;background:#080c10!important}body.keyboard-open .brand:after{display:none}body.keyboard-open .hero{margin-top:0!important}body.keyboard-open .nav{transform:translateY(120%)!important;opacity:0!important;pointer-events:none!important}
.pJobsTitle{font-size:40px;font-weight:900;letter-spacing:-1.3px;margin:4px 0 8px}.pJobsSub{color:var(--pmuted);font-size:18px;margin-bottom:22px}.pGroupTitle{font-size:24px;font-weight:900;margin:24px 2px 10px}.pCount{display:inline-grid;place-items:center;min-width:33px;height:33px;border-radius:50%;margin-left:6px;background:#36414d;color:#d2d8df;font-size:14px}.pCount.gold{background:var(--pgold);color:#111}
@media(max-width:430px){.app{padding-left:12px!important;padding-right:12px!important}.brand{margin-left:-12px!important;margin-right:-12px!important;padding-left:16px!important;padding-right:16px!important}.brandText b{font-size:18px!important}.brandText span{font-size:7px!important}.hero h1{font-size:38px!important}.hero p{font-size:17px!important}.sectionTitle{font-size:34px!important}#content .card:has(#customer) .field{padding-left:62px}.requestTop{gap:8px}.tag{font-size:11px!important}}
`;

const PREMIUM_SCRIPT = String.raw`
<script>(function(){
var lock=false;
function stepFromHero(){var hero=document.getElementById('hero');if(!hero||hero.style.display==='none')return;var pill=hero.querySelector('.pill');var m=pill&&String(pill.textContent||'').match(/(\d)/);var step=m?Number(m[1]):0;if(!step)return;hero.dataset.premiumStep=String(step);var old=hero.querySelector('.premiumProgress');if(old)old.remove();var p=document.createElement('div');p.className='premiumProgress';var bars='';for(var i=1;i<=4;i++)bars+='<i class="'+(i===step?'on':'')+'"></i>';p.innerHTML='<span class="pStep">Шаг '+step+' из 4</span><span class="pBars">'+bars+'</span>';hero.insertBefore(p,hero.firstChild)}
function groupJobs(){if(lock)return;var c=document.getElementById('content');if(!c)return;var title=c.querySelector('.sectionTitle');if(!title||String(title.textContent).trim()!=='Мои заявки')return;var cards=[].slice.call(c.querySelectorAll(':scope > .request'));if(!cards.length)return;if(c.querySelector('.premiumJobsGrouped'))return;lock=true;var sub=c.querySelector('.sectionSub'),active=[],done=[];cards.forEach(function(x){(x.querySelector('.tag.done')?done:active).push(x)});var wrap=document.createElement('div');wrap.className='premiumJobsGrouped';wrap.innerHTML='<div class="pJobsTitle">Мои заявки</div><div class="pJobsSub">Активные и завершённые фотоотчёты</div><div class="pGroupTitle">Активные <span class="pCount gold">'+active.length+'</span></div><div class="pActive"></div><div class="pGroupTitle">Завершённые <span class="pCount">'+done.length+'</span></div><div class="pDone"></div>';c.insertBefore(wrap,c.firstChild);active.forEach(function(x){wrap.querySelector('.pActive').appendChild(x)});done.forEach(function(x){wrap.querySelector('.pDone').appendChild(x)});title.remove();if(sub)sub.remove();lock=false}
function decorate(){if(lock)return;stepFromHero();groupJobs()}
var obs=new MutationObserver(function(){setTimeout(decorate,0)});obs.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['style']});window.addEventListener('load',function(){setTimeout(decorate,100)});
})();</script>`;

export const APP = BASE_APP
  .replace('</style></head>', PREMIUM_CSS + '</style></head>')
  .replace('</body></html>', PREMIUM_SCRIPT + '</body></html>');
