import { APP as BASE } from './app-v13';

function cut(src:string,start:string,end:string,replacement:string){
  const a=src.indexOf(start),b=src.indexOf(end,a+start.length);
  if(a<0||b<0)throw new Error('v15 patch marker not found: '+start);
  return src.slice(0,a)+replacement+src.slice(b);
}

let app=BASE;
app=app.replace('</style>',String.raw`
.focusDim{position:fixed;z-index:210;inset:0;background:rgba(0,0,0,.78);backdrop-filter:blur(4px);opacity:0;pointer-events:none;transition:.18s}.focusDim.on{opacity:1}.field.focused{position:fixed;z-index:220;left:16px;right:16px;top:38vh;transform:translateY(-50%);background:#171a1f;border:1px solid #73591d;border-radius:20px;padding:16px;box-shadow:0 28px 80px #000b}.field.focused .label{font-size:18px}.field.focused input,.field.focused textarea,.field.focused select{font-size:20px;padding:18px}.uploadPulse{animation:pulseGold 1.2s ease-in-out infinite}.waitingOrb{width:92px;height:92px;border-radius:50%;margin:8px auto 12px;display:grid;place-items:center;border:2px solid #8e6a18;background:radial-gradient(circle,#3b2d0b,#17140d 70%);font-size:40px;animation:breathe 2.2s ease-in-out infinite;box-shadow:0 0 34px #e8a41033}.recommend{font-size:15px;line-height:1.5;color:#e6e0cf}.confetti{position:fixed;z-index:400;width:9px;height:14px;top:-20px;border-radius:2px;animation:fall 2.4s linear forwards;pointer-events:none}@keyframes pulseGold{0%,100%{box-shadow:0 0 0 0 #f4b72800}50%{box-shadow:0 0 0 7px #f4b72822}}@keyframes breathe{0%,100%{transform:scale(1)}50%{transform:scale(1.08)}}@keyframes fall{to{transform:translate(var(--x),110vh) rotate(760deg);opacity:.2}}
</style>`);
app=app.replace('<main class="app">','<div id="focusDim" class="focusDim"></div><main class="app">');
app=app.replace('<div id="mediaSheet" class="sheetW"><div class="sheet"><h3>Добавить фото или видео</h3><p>Можно снять сейчас или выбрать несколько файлов из галереи.</p><button id="take" class="sheetBtn"><i>📷</i><span><b>Снять на камеру</b><small>Фото или видео</small></span></button><button id="galleryBtn" class="sheetBtn"><i>🖼</i><span><b>Выбрать из галереи</b><small>Одно или несколько файлов</small></span></button><button id="closeMedia" class="secondary">Отмена</button></div></div>','');
app=app.replace('<input id="cam" type="file" accept="image/*,video/*" capture="environment" hidden><input id="gallery" type="file" accept="image/*,video/*" multiple hidden>','<input id="gallery" type="file" accept="image/*,video/*" multiple hidden>');
app=app.replace("function hero(step,title,sub){$('hero').innerHTML=", "function hero(step,title,sub){$('hero').style.display='block';$('hero').innerHTML=");

app=cut(app,'function wireInputs(){','function geo(){',String.raw`function wireInputs(){
  var a=[].slice.call(document.querySelectorAll('input:not([type=file]):not([type=checkbox]),textarea,select'));
  function place(e){var vv=window.visualViewport;var y=vv?(vv.offsetTop+vv.height*.36):(innerHeight*.36);e.closest('.field').style.top=Math.max(105,y)+'px'}
  a.forEach(function(e,i){
    if(e.tagName==='INPUT')e.setAttribute('enterkeyhint',i<a.length-1?'next':'done');
    e.onfocus=function(){var f=e.closest('.field');if(!f)return;f.classList.add('focused');$('focusDim').classList.add('on');place(e)};
    e.onblur=function(){var f=e.closest('.field');if(f){f.classList.remove('focused');f.style.top=''}$('focusDim').classList.remove('on')};
    e.onkeydown=function(ev){if(ev.key==='Enter'&&e.tagName!=='TEXTAREA'){ev.preventDefault();var n=a[i+1];if(n){e.blur();setTimeout(function(){n.focus()},80)}else e.blur()}}
  });
  if(window.visualViewport)window.visualViewport.onresize=function(){var e=document.querySelector('.field.focused input,.field.focused textarea,.field.focused select');if(e)place(e)};
}
`);

app=cut(app,'function geo(){','async function boot(){',String.raw`function geo(){return new Promise(function(ok,no){
  var best=null,done=false,timer=null,watch=null;
  function finish(){if(done)return;done=true;if(timer)clearTimeout(timer);if(watch!=null&&navigator.geolocation)navigator.geolocation.clearWatch(watch);if(best)return ok(best);telegramFallback()}
  function sample(p){var g={lat:Number(p.coords.latitude),lon:Number(p.coords.longitude),accuracy:Number(p.coords.accuracy||9999)};if(!best||g.accuracy<best.accuracy)best=g;if(g.accuracy<=15)finish()}
  function telegramFallback(){try{var lm=T&&T.LocationManager;if(lm&&typeof lm.init==='function'&&typeof lm.getLocation==='function'){lm.init(function(){if(!lm.isLocationAvailable)return best?ok(best):no(Error('Геопозиция недоступна'));lm.getLocation(function(p){if(!p)return best?ok(best):no(Error('Не удалось определить геопозицию'));var g={lat:Number(p.latitude),lon:Number(p.longitude),accuracy:Number(p.horizontal_accuracy||9999)};if(!best||g.accuracy<best.accuracy)best=g;best?ok(best):no(Error('Не удалось определить геопозицию'))})});return}}catch(e){}best?ok(best):no(Error('Разрешите доступ к геопозиции'))}
  if(navigator.geolocation){try{watch=navigator.geolocation.watchPosition(sample,function(){},{enableHighAccuracy:true,maximumAge:0,timeout:9000});timer=setTimeout(finish,9000);return}catch(e){}}
  telegramFallback();
})}
`);

app=app.replace("function mediaBox(){return'<div class=\"media\"><button id=\"addMedia\" class=\"addMedia\">＋ Добавить фото или видео<small>Снять сейчас или выбрать несколько из галереи</small></button><div id=\"files\" class=\"files\"></div><div id=\"counter\" class=\"counter\">Загрузка сохранённых материалов…</div></div>'}","function mediaBox(){return'<div class=\"media\"><button id=\"addMedia\" class=\"addMedia\">＋ Добавить фото или видео<small>Телефон сам предложит камеру или галерею · можно выбрать несколько файлов</small></button><div id=\"files\" class=\"files\"></div><div id=\"counter\" class=\"counter\">Загрузка сохранённых материалов…</div></div>'}");

app=cut(app,'function bindMedia(st){','async function upload(',String.raw`function bindMedia(st){S.stage=st;$('addMedia').onclick=function(){$('gallery').click()};$('gallery').onchange=function(e){upload([].slice.call(e.target.files||[]),st);e.target.value=''}}
`);

app=app.replace("S.upload++;try{await api('/api/media/draft'","S.upload++;var ab=$('addMedia');if(ab){ab.classList.add('uploadPulse');ab.innerHTML='Сохраняем…<small>Не закрывайте приложение несколько секунд</small>'}try{await api('/api/media/draft'");
app=app.replace("S.upload--}}async function loadFiles","S.upload--;if(ab&&S.upload===0){ab.classList.remove('uploadPulse');ab.innerHTML='＋ Добавить фото или видео<small>Телефон сам предложит камеру или галерею · можно выбрать несколько файлов</small>'}}async function loadFiles");

app=cut(app,'function renderWaiting(){','function renderAfter(){',String.raw`function renderWaiting(){hero(3,'Уборка в процессе','Фото ДО приняты · работайте по регламенту');$('content').innerHTML=stepper(3)+'<div class="card"><div class="success"><div class="waitingOrb">⏱</div><h2 style="font-size:30px">Фото ДО приняты</h2><p class="recommend">Уборка уже зафиксирована. Спокойно выполните работу по регламенту, а после завершения обязательно отправьте фото ПОСЛЕ.</p></div><div id="workTimer" class="timer" style="font-size:44px">00:00</div><div class="timerSub">время с начала уборки</div><div class="reg"><div><i>1</i> Сначала уберите основные поверхности и видимые загрязнения</div><div><i>2</i> Проверьте полы, плинтусы, углы и труднодоступные места</div><div><i>3</i> Отдельно проверьте санузел и мокрые зоны</div><div><i>4</i> Проверьте кухню / рабочую зону</div><div><i>5</i> Перед фото ПОСЛЕ сделайте финальный осмотр</div></div><div class="hint"><i>✦</i><span>Совет: снимайте ПОСЛЕ примерно с тех же ракурсов, что и ДО — руководителю будет легче сравнить результат.</span></div><button id="afterGo" class="primary">Перейти к фото ПОСЛЕ →</button><button id="problemBtn" class="secondary">Связаться с администратором</button></div>';$('afterGo').onclick=function(){S.showAfter=true;renderAfter()};$('problemBtn').onclick=openContact;var started=Number(S.job&&S.job.startedAt||Date.now());function tick(){var s=Math.max(0,Math.floor((Date.now()-started)/1000)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),ss=s%60;$('workTimer').textContent=(h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(ss).padStart(2,'0')}tick();S.timer=setInterval(tick,1000)}
`);

app=cut(app,'function renderDone(x){','function renderJobs(){',String.raw`function celebrate(){for(var i=0;i<34;i++){var d=document.createElement('i');d.className='confetti';d.style.left=(Math.random()*100)+'vw';d.style.background=['#f4b728','#fff1a8','#d9950c','#ffffff'][i%4];d.style.setProperty('--x',((Math.random()-.5)*180)+'px');d.style.animationDelay=(Math.random()*.45)+'s';document.body.appendChild(d);setTimeout(function(n){return function(){n.remove()}}(d),3100)}}function renderDone(x){hero(4,'Фотоотчёт завершён','Данные сохранены и отправляются руководителю');$('content').innerHTML='<div class="card success"><div class="successIcon">✓</div><h2>Готово</h2><p>Фото ДО и ПОСЛЕ приняты.<br>Время работы: <b>'+esc(x&&x.duration_text||'—')+'</b><br>Номер отчёта: <b>'+esc(x&&x.report_id||S.job&&S.job.reportId||'—')+'</b></p><button id="newAgain" class="primary">Новый фотоотчёт</button></div>';$('newAgain').onclick=function(){S.job=null;renderStart()};celebrate()}
`);

app=cut(app,'function renderJobs(){','function renderProfile(){',String.raw`async function renderJobs(){hero(1,'Мои заявки','Текущие и завершённые фотоотчёты');$('content').innerHTML='<h2 class="sectionTitle">Мои заявки</h2><div class="card noData">Загружаем историю…</div>';try{var x=await api('/api/history'),a=x.jobs||[];if(!a.length){$('content').innerHTML='<h2 class="sectionTitle">Мои заявки</h2><div class="card noData"><strong>▤</strong>У вас пока нет фотоотчётов.<button id="goNew" class="primary">Начать фотоотчёт</button></div>';$('goNew').onclick=function(){nav('new')};return}var html='<h2 class="sectionTitle">Мои заявки</h2><p class="sectionSub">Сохраняются текущие и завершённые уборки.</p>';a.forEach(function(j){var st=j.stage==='done'?'Завершена':j.stage==='before_sent'?'В процессе':'Ожидается ДО';var col=j.stage==='done'?'style="background:#123122;color:#7ee2aa"':'';html+='<div class="request"><div class="requestTop"><b>'+esc(j.customer||'Без имени')+'</b><span class="tag" '+col+'>'+st+'</span></div><div class="requestMeta"><span>⌖ '+esc(j.address||'—')+'</span><span>☷ '+esc(j.type||'—')+'</span><span>Начало: '+fmt(j.startedAt)+'</span>'+(j.finishedAt?'<span>Завершено: '+fmt(j.finishedAt)+'</span>':'')+(j.reportId?'<span>Отчёт: '+esc(j.reportId)+'</span>':'')+'</div>'+(j.stage!=='done'&&S.job&&j.id===S.job.id?'<button class="primary openCurrent">Продолжить текущую уборку</button>':'')+'</div>'});$('content').innerHTML=html;document.querySelectorAll('.openCurrent').forEach(function(b){b.onclick=function(){nav('new')}})}catch(e){$('content').innerHTML='<h2 class="sectionTitle">Мои заявки</h2><div class="card noData">'+esc(e.message)+'</div>'}}
`);

app=cut(app,'function renderProfile(){','function renderRules(){',String.raw`function renderProfile(){$('hero').style.display='none';var name=employeeName(),id=S.employee&&S.employee.id?S.employee.id:'—',letter=name.trim().charAt(0).toUpperCase()||'H';$('content').innerHTML='<div style="height:6px"></div><div class="card"><div class="profileHead"><div class="avatar">'+esc(letter)+'</div><div><h2>'+esc(name)+'</h2><p>Telegram ID: '+esc(id)+' · '+(S.admin?'Администратор':'Сотрудник')+'</p></div></div></div><button id="rulesBtn" class="menuBtn"><i>▤</i><span><b>Правила и регламент</b><small>Правила компании и порядок работы</small></span><em>›</em></button><button id="guideBtn" class="menuBtn"><i>◉</i><span><b>Как делать фотоотчёт</b><small>Простая инструкция ДО и ПОСЛЕ</small></span><em>›</em></button><button id="contactBtn" class="menuBtn"><i>✉</i><span><b>Связаться с администратором</b><small>Проблема или вопрос по объекту</small></span><em>›</em></button><button id="helpBtn" class="menuBtn"><i>?</i><span><b>Помощь</b><small>Камера, интернет, GPS и восстановление</small></span><em>›</em></button>';$('rulesBtn').onclick=renderRules;$('guideBtn').onclick=renderGuide;$('contactBtn').onclick=openContact;$('helpBtn').onclick=renderHelp}
`);

app=cut(app,'function renderRules(){','function renderGuide(){',String.raw`function renderRules(){$('hero').style.display='none';$('content').innerHTML='<button id="backProfile" class="backBtn">← Назад в профиль</button><div class="card article"><h3>1. Перед началом</h3><ul><li>Начинайте фотоотчёт только после прибытия на нужный объект.</li><li>Проверьте имя клиента, адрес и тип уборки.</li><li>До основной уборки обязательно зафиксируйте состояние помещений.</li></ul><h3>2. Фото и видео ДО</h3><ul><li>Снимите общий вид и основные рабочие зоны.</li><li>Царапины, сколы, пятна, поломки и другие дефекты снимайте крупно и понятно.</li><li>Материалы должны быть сделаны на текущем объекте и соответствовать реальному состоянию.</li></ul><h3>3. Регламент уборки</h3><ul><li>Поверхности и видимые загрязнения.</li><li>Полы, плинтусы, углы и труднодоступные места.</li><li>Санузел и мокрые зоны.</li><li>Кухонная / рабочая зона.</li><li>Перед завершением — финальный осмотр.</li></ul><h3>4. Фото и видео ПОСЛЕ</h3><ul><li>Снимите готовый результат и основные зоны.</li><li>По возможности повторяйте ракурсы ДО.</li><li>Не завершайте отчёт, пока результат уборки не проверен.</li></ul><h3>5. Проблемы на объекте</h3><p>Спор с клиентом, дополнительная работа, повреждение, отсутствие доступа, проблемы с техникой или другие нестандартные ситуации сразу передавайте администратору через приложение.</p><h3>6. Ответственность</h3><p>Обязательный фотоотчёт является частью внутреннего регламента House Cleaning. Первый пропуск — штраф согласно условиям компании, повторный пропуск может стать основанием для расторжения договора.</p></div>';$('backProfile').onclick=renderProfile}
`);

app=cut(app,'function renderHelp(){','function openContact(){',String.raw`function renderHelp(){$('hero').style.display='none';$('content').innerHTML='<button id="backProfile" class="backBtn">← Назад в профиль</button><div class="card article"><h3>GPS неточный</h3><p>Включите точную геопозицию для Telegram, подойдите к окну или выйдите на открытое место. Приложение несколько секунд ищет лучший доступный GPS-сигнал.</p><h3>Фото не загружается</h3><p>Проверьте интернет. Не закрывайте Mini App во время сохранения файла. Уже сохранённые материалы останутся после повторного открытия.</p><h3>Случайно закрыли приложение</h3><p>Откройте бот снова — активная уборка восстановится с нужного этапа.</p><button id="helpContact" class="primary">Связаться с администратором</button></div>';$('backProfile').onclick=renderProfile;$('helpContact').onclick=openContact}
`);

export const APP=app;
