import { APP as BASE } from './app-v9';

const NEW_RENDER = "function render(){var j=S.job;if(S.waitTimer){clearInterval(S.waitTimer);S.waitTimer=null}if(!j||j.stage==='done')return start();if(j.stage==='started')return before();return waiting()}";

const WAITING = `function waiting(){S.stage='waiting';var j=S.job;status('Уборка в процессе','Фото/видео ДО принято',true);var started=Number(j.startedAt||Date.now());$('screen').innerHTML='<section class="card done" style="text-align:left"><strong style="display:block;text-align:center">✅</strong><h2 style="text-align:center;margin:8px 0">Фото ДО отправлены</h2><p style="text-align:center;color:var(--m);line-height:1.5">Выполните уборку по регламенту. Когда закончите — перейдите к фото/видео ПОСЛЕ.</p><div class="reg" style="margin-top:14px"><div>🧽 Поверхности и видимые загрязнения</div><div>🧹 Полы, плинтусы и углы</div><div>🚿 Санузел / мокрые зоны</div><div>🍽 Кухонная / рабочая зона</div><div>👀 Финальный осмотр перед съёмкой</div></div><div class="gps" style="margin-top:14px"><div><b id="workTime">00:00</b><span>время на объекте</span></div><div><b>'+esc(j.customer||'—')+'</b><span>клиент</span></div></div><button id="problemBtn" class="ghost" style="width:100%;margin-top:12px">🆘 Есть проблема на объекте</button></section>';$('go').textContent='Перейти к фото ПОСЛЕ';$('go').disabled=false;$('go').onclick=after;function tick(){var sec=Math.max(0,Math.floor((Date.now()-started)/1000)),h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;var el=$('workTime');if(el)el.textContent=(h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}tick();S.waitTimer=setInterval(tick,1000);var pb=$('problemBtn');if(pb)pb.onclick=function(){$('help').click()}}`;

const NEW_AFTER = `function after(){if(S.waitTimer){clearInterval(S.waitTimer);S.waitTimer=null}S.stage='after';status('Финиш уборки','Добавьте фото/видео ПОСЛЕ',true);$('screen').innerHTML='<section class="card"><div class="head"><div class="title">Фото и видео ПОСЛЕ</div><span class="badge">ШАГ 4</span></div><div class="tip" style="margin-bottom:12px">✨ Снимите готовый результат: общий вид и основные зоны. Дефекты повторно отмечать не нужно.</div>'+box()+'<label class="confirm"><input id="truth" type="checkbox"><span>Материалы показывают реальный результат ПОСЛЕ уборки.</span></label></section>';bind('after');$('go').textContent='Завершить уборку';$('go').disabled=false;$('go').onclick=sendAfter;loadFiles('after')}`;

export const APP = BASE
  .replace("function render(){var j=S.job;if(!j||j.stage==='done')return start();if(j.stage==='started')return before();return after()}", NEW_RENDER)
  .replace(/function after\(\)\{S\.stage='after';[\s\S]*?loadFiles\('after'\)\}/, WAITING + NEW_AFTER);
