export interface Env { AI: Ai; TELEGRAM_BOT_TOKEN: string; }
const TELEGRAM_API=(t:string)=>`https://api.telegram.org/bot${t}`;
const TELEGRAM_FILE_API=(t:string)=>`https://api.telegram.org/file/bot${t}`;
const VISION_MODEL="@cf/qwen/qwen3.8-27b";
const MAX_IMAGE_BYTES=8*1024*1024;
const SYSTEM_PROMPT=`Ты — аккуратный консультант по символической интерпретации Таро. Никогда не придумывай карты. Если карта неразборчива, укажи card_name=null и confidence=low. Не утверждай, что знаешь будущее наверняка и не давай гарантированных предсказаний. Сначала распознай только реально видимые карты, их порядок и положение. Затем интерпретируй весь расклад в контексте вопроса. Если схема расклада неизвестна, честно укажи это. Ответ на русском языке.`;
interface TarotCard{position:number;card_name:string|null;orientation:"upright"|"reversed"|"unknown";confidence:"high"|"medium"|"low"}
interface TarotResult{readable:boolean;deck:string;cards:TarotCard[];spread_type:string;analysis:string;conclusion:string;advice:string}
interface TelegramUpdate{update_id:number;message?:{message_id:number;chat:{id:number};photo?:Array<{file_id:string;width:number;height:number;file_size?:number}>;caption?:string;text?:string}}
export default{async fetch(request:Request,env:Env):Promise<Response>{if(request.method==="GET")return new Response("Tarot bot is running");if(request.method!=="POST")return new Response("Method Not Allowed",{status:405});let update:TelegramUpdate|undefined;try{update=await request.json<TelegramUpdate>();await handleUpdate(update,env)}catch(error){console.error("[TAROT BOT] Update processing error:",error);console.error("[TAROT BOT] Error stack:",error instanceof Error?error.stack:String(error));const chatId=update?.message?.chat.id;if(chatId){const detail=error instanceof Error?error.message:String(error);const userMessage=/size|large|bytes|too large/i.test(detail)?"Фото слишком большое. Пришлите фото меньшего размера.":"Не удалось обработать расклад. Попробуйте ещё раз. Ошибка записана в логах Cloudflare.";await sendMessage(env.TELEGRAM_BOT_TOKEN,chatId,userMessage)}}return new Response("OK")}} satisfies ExportedHandler<Env>;
async function handleUpdate(update:TelegramUpdate,env:Env){const m=update.message;if(!m)return;const t=env.TELEGRAM_BOT_TOKEN,c=m.chat.id;if(m.text==="/start"){await sendMessage(t,c,"🔮 Добро пожаловать.\n\nОтправьте фото расклада Таро и вопрос в подписи. Я сначала определю видимые карты, их положение и порядок, затем дам разбор по вопросу. Если карта не читается уверенно, я не буду её придумывать.");return}if(!m.photo?.length){await sendMessage(t,c,"Пришлите фотографию расклада Таро и вопрос в подписи.");return}const q=(m.caption||"").trim();if(!q){await sendMessage(t,c,"Фото получил. Добавьте вопрос в подписи к фотографии и отправьте ещё раз.");return}await sendMessage(t,c,"Фото получил. Анализирую карты и ваш вопрос. Если карта не читается уверенно, я отмечу это, а не буду угадывать.");const p=m.photo[m.photo.length-1];const file=await getTelegramFile(t,p.file_id);const result=await analyzeTarot(env,file.url,q);await sendMessage(t,c,formatTarotResult(result,q))}
async function getTelegramFile(t:string,id:string):Promise<{url:string;mime:string}> {const r=await fetch(`${TELEGRAM_API(t)}/getFile?file_id=${encodeURIComponent(id)}`);if(!r.ok)throw new Error(`Telegram getFile HTTP ${r.status}`);const j=await r.json<any>();if(!j.ok||!j.result?.file_path)throw new Error(`Telegram getFile failed: ${JSON.stringify(j)}`);const path=String(j.result.file_path);const url=`${TELEGRAM_FILE_API(t)}/${path}`;const head=await fetch(url,{method:"HEAD"});const n=Number(head.headers.get("content-length")||0);if(n>MAX_IMAGE_BYTES)throw new Error(`Image too large: ${n} bytes`);const mime=(head.headers.get("content-type")||"image/jpeg").split(";")[0];return{url,mime:mime.startsWith("image/")?mime:"image/jpeg"}}
async function analyzeTarot(env:Env,imageUrl:string,q:string):Promise<TarotResult>{const prompt=`Вопрос пользователя:\n${q}\n\nПроанализируй фотографию расклада Таро. Сначала определи только реально видимые карты и их порядок. Для каждой карты укажи название, положение и confidence. Если карта неразборчива — card_name=null. Затем дай общий анализ всех карт именно в контексте вопроса. Не выдумывай схему расклада, если она неочевидна. Верни только JSON следующего вида:\n{"readable":true,"deck":"...","cards":[{"position":1,"card_name":"...","orientation":"upright","confidence":"high"}],"spread_type":"...","analysis":"...","conclusion":"...","advice":"..."}`;console.log("[TAROT BOT] Sending image URL to Workers AI",{model:VISION_MODEL});const response=await env.AI.run(VISION_MODEL,{messages:[{role:"system",content:SYSTEM_PROMPT},{role:"user",content:[{type:"image_url",image_url:{url:imageUrl}},{type:"text",text:prompt}]}],max_tokens:2200,temperature:0.15} as any);console.log("[TAROT BOT] Workers AI response received",{responseType:typeof response});const raw=typeof response==="string"?response:(response as any)?.response;if(!raw)throw new Error(`Workers AI returned empty response: ${JSON.stringify(response)}`);return normalizeTarotResult(parseJsonObject(raw))}
function parseJsonObject(raw:string):any{try{return JSON.parse(raw)}catch{const s=raw.indexOf("{"),e=raw.lastIndexOf("}");if(s>=0&&e>s)return JSON.parse(raw.slice(s,e+1));throw new Error(`Workers AI returned non-JSON response: ${raw.slice(0,500)}`)}}
function normalizeTarotResult(v:any):TarotResult{const cards:Array<TarotCard>=Array.isArray(v?.cards)?v.cards.map((x:any,i:number)=>({position:Number.isFinite(Number(x?.position))?Number(x.position):i+1,card_name:typeof x?.card_name==="string"&&x.card_name.trim()?x.card_name.trim():null,orientation:["upright","reversed","unknown"].includes(x?.orientation)?x.orientation:"unknown",confidence:["high","medium","low"].includes(x?.confidence)?x.confidence:"low"})):[];return{readable:Boolean(v?.readable??cards.some(x=>x.card_name)),deck:typeof v?.deck==="string"?v.deck:"Не определена",cards,spread_type:typeof v?.spread_type==="string"?v.spread_type:"Схема не определена",analysis:typeof v?.analysis==="string"?v.analysis:"Не удалось сформировать анализ.",conclusion:typeof v?.conclusion==="string"?v.conclusion:"Не удалось сформировать итог.",advice:typeof v?.advice==="string"?v.advice:"Не удалось сформировать совет."}}
function formatTarotResult(r:TarotResult,q:string){if(!r.cards.length||!r.cards.some(c=>c.card_name))return"Я не смог уверенно распознать карты на фотографии. Не хочу угадывать.\n\nПришлите фото крупнее, чтобы все карты были хорошо видны.";const lines=r.cards.map(c=>`${c.position}. ${c.card_name||"Карта не определена"}${c.orientation==="reversed"?" — перевёрнутая":c.orientation==="upright"?" — прямая":" — положение не определено"} (${c.confidence})`).join("\n");return`🔮 РАЗБОР РАСКЛАДА\n\nВопрос: ${q}\n\nКарты:\n${lines}\n\nСхема: ${r.spread_type}\n\nОБЩИЙ АНАЛИЗ\n${r.analysis}\n\nИТОГ\n${r.conclusion}\n\nСОВЕТ\n${r.advice}\n\nЭто символическая интерпретация Таро, а не гарантированное предсказание будущего.`}
async function sendMessage(t:string,c:number,text:string){const r=await fetch(`${TELEGRAM_API(t)}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:c,text,disable_web_page_preview:true})});if(!r.ok)console.error("[TAROT BOT] Telegram sendMessage failed",await r.text())}
