import { APP } from './app';
export interface Env { TELEGRAM_BOT_TOKEN:string; ADMIN_IDS?:string; WEBAPP_URL?:string }
const API=(t:string)=>`https://api.telegram.org/bot${t}`;
export default {async fetch(req:Request,env:Env):Promise<Response>{const u=new URL(req.url);if(req.method==='GET'&&u.pathname==='/')return new Response(APP,{headers:{'content-type':'text/html;charset=utf-8'}});if(req.method==='GET'&&u.pathname==='/health')return J({ok:true,bot:'hcbototcet',service:'photo-reports'});if(req.method==='POST'&&u.pathname==='/webhook'){try{await update(await req.json<any>(),env,req)}catch(e){console.error(e)}return new Response('OK')}if(req.method==='POST'&&u.pathname==='/api/report')return report(req,env);return new Response('Not found',{status:404})}} satisfies ExportedHandler<Env>;
async function update(x:any,e:Env,r:Request){const m=x?.message;if(!m?.chat?.id)return;const url=e.WEBAPP_URL||new URL(r.url).origin+'/',kb={inline_keyboard:[[{text:'Создать фотоотчёт',web_app:{url}}]]};return send(e.TELEGRAM_BOT_TOKEN,m.chat.id,'<b>HOUSE CLEANING</b>\n\nФотоотчёты после уборки.\n\nНажмите кнопку ниже, выберите объект и добавьте фото ДО/ПОСЛЕ.',{parse_mode:'HTML',reply_markup:kb})}
async function report(req:Request,e:Env){const u=await auth(req.headers.get('X-Telegram-Init-Data')||'',e.TELEGRAM_BOT_TOKEN);if(!u)return J({ok:false,error:'Откройте приложение из Telegram заново.'},401);const f=await req.formData(),object=String(f.get('object')||'').trim(),comment=String(f.get('comment')||'').trim(),before=f.getAll('before').filter((x):x is File=>x instanceof File),after=f.getAll('after').filter((x):x is File=>x instanceof File),files=[...before,...after];if(!object)return J({ok:false,error:'Укажите объект.'},400);if(!files.length)return J({ok:false,error:'Добавьте фото.'},400);if(files.length>20)return J({ok:false,error:'Максимум 20 фото.'},400);if(files.some(x=>!x.type.startsWith('image/')||x.size>10*1024*1024))return J({ok:false,error:'Фото должны быть до 10 МБ.'},400);const admins=(e.ADMIN_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);if(!admins.length)return J({ok:false,error:'В Cloudflare не задан ADMIN_IDS.'},500);const cap=['<b>НОВЫЙ ФОТООТЧЁТ</b>',`Объект: <b>${esc(object)}</b>`,`Сотрудник: ${esc(name(u))}`,`Telegram ID: <code>${u.id}</code>`,`Фото: ${files.length}`,comment?`Комментарий: ${esc(comment)}`:''].filter(Boolean).join('\n');for(const a of admins){await send(e.TELEGRAM_BOT_TOKEN,a,cap,{parse_mode:'HTML'});for(let i=0;i<files.length;i+=10)await media(e.TELEGRAM_BOT_TOKEN,a,files.slice(i,i+10),i,before.length)}return J({ok:true,photos:files.length})}
async function media(t:string,chat:string,files:File[],off:number,before:number){const f=new FormData(),m:any[]=[];files.forEach((x,i)=>{const n=`f${off+i}`,label=off+i<before?`ДО #${off+i+1}`:`ПОСЛЕ #${off+i-before+1}`;f.append(n,x,x.name||n);m.push({type:'photo',media:`attach://${n}`,caption:label})});f.append('chat_id',chat);f.append('media',JSON.stringify(m));const r=await fetch(`${API(t)}/sendMediaGroup`,{method:'POST',body:f});if(!r.ok)throw Error(await r.text())}
async function send(t:string,id:string|number,text:string,x:any={}){return (await fetch(`${API(t)}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:id,text,...x})})).json()}
async function auth(raw:string,t:string){if(!raw)return null;try{const p=new URLSearchParams(raw),h=p.get('hash'),d=Number(p.get('auth_date')||0);if(!h||Date.now()/1000-d>86400)return null;p.delete('hash');const s=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([a,b])=>`${a}=${b}`).join('\n'),k=await crypto.subtle.importKey('raw',new TextEncoder().encode('WebAppData'),{name:'HMAC',hash:'SHA-256'},false,['sign']),secret=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(t)),k2=await crypto.subtle.importKey('raw',secret,{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=await crypto.subtle.sign('HMAC',k2,new TextEncoder().encode(s)),got=[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,'0')).join('');return got===h?JSON.parse(p.get('user')||'null'):null}catch{return null}}
const name=(u:any)=>[u.first_name,u.last_name].filter(Boolean).join(' ')||u.username||'Сотрудник';const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});