import { STAFF_FINAL_APP } from './staff-final-ui';

const PROD_CSS = String.raw`
<style>
/* Production polish: payments + readable company standards */
.payment-replace-note{margin-top:10px;padding:11px 12px;border-radius:13px;background:#eef5ff;border:1px solid #cfe0ff;color:#315f9a;font-size:12px;line-height:1.4}
.payment-replace-note b{color:#174f9b}.payout-bank{display:inline-flex;align-items:center;gap:5px;margin-left:5px;padding:3px 7px;border-radius:999px;background:#edf4ff;color:#1769e0;border:1px solid #cfe0ff;font-size:10px;font-weight:800}
.standards-legend{display:flex;gap:7px;overflow:auto;padding:0 0 11px;scrollbar-width:none}.standards-legend::-webkit-scrollbar{display:none}.standards-legend span{white-space:nowrap;padding:6px 9px;border-radius:999px;font-size:11px;font-weight:800;border:1px solid #dfe5ee;background:#fff}.standard-card{position:relative;overflow:hidden;border-left-width:5px!important}.standard-card:before{content:attr(data-kind);display:inline-flex;margin-bottom:9px;border-radius:999px;padding:4px 8px;font-size:10px;font-weight:850;letter-spacing:.2px}.standard-card.std-blue{border-left-color:#1769e0!important;background:linear-gradient(90deg,#f4f8ff,#fff 34%)}.standard-card.std-blue:before{content:'ПОРЯДОК РАБОТЫ';background:#e8f1ff;color:#1558b5}.standard-card.std-green{border-left-color:#15945b!important;background:linear-gradient(90deg,#f0fbf5,#fff 34%)}.standard-card.std-green:before{content:'КАЧЕСТВО';background:#def5e9;color:#117549}.standard-card.std-orange{border-left-color:#e18a19!important;background:linear-gradient(90deg,#fff7e9,#fff 34%)}.standard-card.std-orange:before{content:'ОСТОРОЖНО';background:#ffedc9;color:#995b08}.standard-card.std-red{border-left-color:#d54a4a!important;background:linear-gradient(90deg,#fff2f2,#fff 34%)}.standard-card.std-red:before{content:'ВАЖНО';background:#ffe0e0;color:#a72d2d}.standard-card.std-purple{border-left-color:#7657c7!important;background:linear-gradient(90deg,#f7f3ff,#fff 34%)}.standard-card.std-purple:before{content:'КЛИЕНТ И СЕРВИС';background:#ece5ff;color:#5e43a7}.standard-card h3{font-size:17px!important;margin-bottom:7px!important}.standard-card p{color:#465365!important;font-size:13px!important;line-height:1.55!important}.std-intro{background:#fff;border:1px solid #dfe5ee;border-radius:16px;padding:12px 13px;margin-bottom:10px;color:#596577;font-size:12px}.std-intro b{color:#1f2b3b}.finance-tile .bank-line{font-size:10px;color:#1769e0;font-weight:750;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
</style>`;

const PROD_PATCH = String.raw`
/* PRODUCTION PATCH — inside the main STAFF closure */
function hcProdPayoutMethod(r){if(!r)return'';var a=[];if(r.payment_bank)a.push(r.payment_bank);if(r.payment_sbp_phone)a.push('СБП '+r.payment_sbp_phone);else if(r.payment_card_last4)a.push('•••• '+r.payment_card_last4);return a.join(' · ')}
function hcProdCurrentPaymentText(p){p=p||{};var a=[];if(p.bank)a.push(p.bank);if(p.sbp_phone)a.push('СБП '+p.sbp_phone);if(p.recipient)a.push(p.recipient);if(p.card_last4)a.push('карта •••• '+p.card_last4);return a.join(' · ')||'реквизиты ещё не указаны'}
function hcProdSamePayment(a,b){return String(a.bank||'')===String(b.bank||'')&&String(a.sbp_phone||'')===String(b.sbp_phone||'')&&String(a.recipient||'')===String(b.recipient||'')&&String(a.card_last4||'')===String(b.card_last4||'')}

hcHistory=function(rows){if(!rows||!rows.length)return '<div class="empty">Операций пока нет</div>';return rows.map(function(r){var payout=r.type==='payout',plus=!payout&&Number(r.amount||0)>=0,sign=payout?'-':(Number(r.amount||0)>=0?'+':''),method=hcProdPayoutMethod(r);return '<div class="history-row"><div><div class="h-title">'+H(r.label||r.type)+(method?'<span class="payout-bank">'+H(method)+'</span>':'')+'</div><div class="h-sub">'+(r.address?H(r.address)+' · ':'')+fmt(r.at)+(r.comment?' · '+H(r.comment):'')+'</div></div><div class="h-amount '+(payout?'minus':plus?'plus':'minus')+'">'+sign+money(Math.abs(Number(r.amount||0)))+'</div></div>'}).join('')};

financeEntry=async function(e,kind){try{var amount=prompt(kind==='payout'?'Сумма выплаты, ₽':'Сумма корректировки (можно со знаком -), ₽');if(amount===null)return;var n=Number(String(amount).replace(',','.'));if(!isFinite(n)||(kind==='payout'&&n<=0)||(kind==='adjustment'&&n===0)){toast('Проверьте сумму');return}var comment=prompt('Комментарий / причина')||'',pay={};if(kind==='payout'){var px=await api('/api/staff/payment-details?id='+encodeURIComponent(e.id));pay=px.payment||{};var method=hcProdCurrentPaymentText(pay);if(!confirm('Отметить выплату '+money(n)+'?\n\nКуда: '+method))return}await api('/api/staff/finance/entry',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({employee_id:e.id,kind:kind,amount:n,comment:comment})});toast(kind==='payout'?'Выплата сохранена':'Корректировка сохранена');employeeDetail(e.id)}catch(x){toast(x.message)}};

var hcProdEmployeeDetail=employeeDetail;
employeeDetail=async function(id){await hcProdEmployeeDetail(id);try{var a=await Promise.all([api('/api/staff/employee-finance?id='+encodeURIComponent(id)),api('/api/staff/payment-details?id='+encodeURIComponent(id))]),f=a[0],pay=a[1].payment||{},last=(f.history||[]).find(function(x){return x.type==='payout'}),method=hcProdPayoutMethod(last)||pay.bank||'';var tiles=document.querySelectorAll('.finance-grid .finance-tile');if(tiles[1]){var span=tiles[1].querySelector('span');if(span)span.innerHTML='выплачено'+(method?'<div class="bank-line">'+H(method)+'</div>':'')}var box=document.getElementById('savepay')&&document.getElementById('savepay').parentElement;if(box&&!box.querySelector('.payment-replace-note'))box.insertAdjacentHTML('beforeend','<div class="payment-replace-note"><b>Актуальные реквизиты одни.</b> При сохранении новые данные полностью заменят предыдущие. Изменение фиксируется в журнале.</div>');var btn=document.getElementById('savepay');if(btn)btn.onclick=async function(){try{var cur=(await api('/api/staff/payment-details?id='+encodeURIComponent(id))).payment||{},next={bank:document.getElementById('pbank').value,sbp_phone:document.getElementById('psbp').value,recipient:document.getElementById('prec').value,card_last4:document.getElementById('plast').value};if(hcProdSamePayment(cur,next)){toast('Реквизиты не изменились');return}if((cur.bank||cur.sbp_phone||cur.recipient||cur.card_last4)&&!confirm('Заменить текущие реквизиты сотрудника новыми?'))return;await api('/api/staff/payment-details?id='+encodeURIComponent(id),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(next)});toast('Новые реквизиты сохранены');await reloadAdmin();employeeDetail(id)}catch(x){toast(x.message)}}}catch(e){}}

var hcProdProfile=profile;
profile=async function(){await hcProdProfile();try{var a=await Promise.all([api('/api/staff/my-finance'),api('/api/staff/payment-details')]),f=a[0],pay=a[1].payment||{},last=(f.history||[]).find(function(x){return x.type==='payout'}),method=hcProdPayoutMethod(last)||pay.bank||'';var tiles=document.querySelectorAll('.finance-grid .finance-tile');if(tiles[1]){var span=tiles[1].querySelector('span');if(span)span.innerHTML='выплачено'+(method?'<div class="bank-line">'+H(method)+'</div>':'')}var btn=document.getElementById('savemypay'),box=btn&&btn.parentElement;if(box&&!box.querySelector('.payment-replace-note'))box.insertAdjacentHTML('beforeend','<div class="payment-replace-note"><b>Реквизиты можно менять самостоятельно.</b> Новые полностью заменят предыдущие, а руководитель сразу получит уведомление об изменении.</div>');if(btn)btn.onclick=async function(){try{var cur=(await api('/api/staff/payment-details')).payment||{},next={bank:document.getElementById('mybank').value,sbp_phone:document.getElementById('mysbp').value,recipient:document.getElementById('myrec').value,card_last4:document.getElementById('mylast').value};if(hcProdSamePayment(cur,next)){toast('Реквизиты не изменились');return}if((cur.bank||cur.sbp_phone||cur.recipient||cur.card_last4)&&!confirm('Заменить текущие реквизиты новыми? Руководителю придёт уведомление.'))return;await api('/api/staff/payment-details',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(next)});toast('Реквизиты обновлены. Руководитель уведомлён.');profile()}catch(x){toast(x.message)}}}catch(e){}}

standards=function(){var items=[
['blue','Перед выездом','Проверьте адрес, дату, время, вид уборки, площадь и дополнительные услуги. Если понимаете, что опаздываете или не сможете выйти — сразу сообщите руководителю.'],
['green','Фото ДО','Снимайте объект до начала работ с понятных общих ракурсов. Отдельно фиксируйте уже существующие повреждения. Не фотографируйте документы и личные данные клиента.'],
['blue','Порядок уборки','Работайте по зонам: сверху вниз, от более чистого к загрязнённому. Не перескакивайте хаотично между комнатами. Перед уходом обязательна финальная проверка.'],
['orange','Химия и безопасность','Работайте в перчатках и соблюдайте дозировки. Не смешивайте хлор с кислотами и неизвестные средства между собой. Новое средство сначала тестируйте на незаметном участке.'],
['orange','Поверхности','Натуральный камень — без кислот. Дерево и ламинат — минимум влаги. Глянцевые и деликатные поверхности — мягкая микрофибра без абразива. Нержавейку протирайте по направлению текстуры.'],
['green','Генеральная уборка','Сначала верхние поверхности, затем мебель и вертикали, кухня и санузлы, после — полы. Проверяйте труднодоступные места, плинтусы, двери, выключатели и зоны за мебелью, если это входит в заказ.'],
['orange','После ремонта','Главная задача — строительная пыль. Удаляйте её поэтапно, не размазывайте влажной тряпкой сразу. Для следов материалов используйте только подходящие составы и не экспериментируйте на видимых участках.'],
['purple','Общение с клиентом','Будьте спокойны и вежливы. Не меняйте цену, состав работ и обещания от имени компании без руководителя. Спорные вопросы сразу передавайте руководителю.'],
['red','Имущество клиента','При повреждении или обнаруженном дефекте ничего не скрывайте: остановитесь, сделайте фото и сразу сообщите руководителю. Не перемещайте ценные вещи без необходимости.'],
['red','Ключи и доступ','Не передавайте ключи третьим лицам, не фотографируйте коды доступа и не храните их вне рабочего процесса. После заказа действуйте строго по инструкции руководителя.'],
['purple','Внешний вид','Чистая рабочая одежда, аккуратный вид, сменная обувь при необходимости. Не используйте резкие личные ароматы на объекте.'],
['red','Конфиденциальность','Адреса, телефоны, фото объектов и любая информация о клиентах — только для выполнения заказа. Не публикуйте и не пересылайте их посторонним.'],
['green','Фото ПОСЛЕ','Повторите ключевые ракурсы ДО, покажите результат и важные зоны. Проверьте, что фото загрузились, затем закройте чек-лист и отправьте отчёт.'],
['red','Нестандартная ситуация','Конфликт, опасная поверхность, поломка, отсутствие доступа, клиент просит дополнительные работы или меняет условия — не принимайте решение самостоятельно. Свяжитесь с руководителем.']
];function draw(q){q=String(q||'').toLowerCase();var a=items.filter(function(x){return !q||(x[1]+' '+x[2]).toLowerCase().indexOf(q)>=0});document.getElementById('stdlist').innerHTML=a.length?a.map(function(x){return '<div class="standard-card std-'+x[0]+'"><h3>'+H(x[1])+'</h3><p>'+H(x[2])+'</p></div>'}).join(''):'<div class="card empty">Ничего не найдено</div>'}M((S.state&&S.state.admin?'<button id="stdback" class="back">← Ещё</button>':'')+'<div class="hero"><h1>Стандарты HOUSE CLEANING</h1><p>Рабочий регламент — быстро и без путаницы.</p></div><div class="std-intro"><b>Цвет помогает ориентироваться:</b> синий — порядок работы, зелёный — качество, жёлтый — осторожность, красный — критически важно, фиолетовый — клиент и сервис.</div><div class="standards-legend"><span>🔵 Порядок</span><span>🟢 Качество</span><span>🟠 Осторожно</span><span>🔴 Важно</span><span>🟣 Сервис</span></div><input id="stdsearch" class="search" placeholder="Поиск: химия, фото, клиент, поверхность…"><div id="stdlist" class="standards-list"></div>');draw('');document.getElementById('stdsearch').oninput=function(){draw(this.value)};var b=document.getElementById('stdback');if(b)b.onclick=function(){go('more')}};
cheatSheet=standards;
`;

const anchor = 'boot();\\\n})();\\\n</script>';
const patched = STAFF_FINAL_APP.replace(anchor, PROD_PATCH + '\\\nboot();\\\n})();\\\n</script>');
export const STAFF_PRODUCTION_APP = patched.replace('</body>', PROD_CSS + '</body>');
