const APP_MOTION_CSS = String.raw`
<style>
/* HOUSE CLEANING STAFF motion system: event-driven, transform/opacity first. */
.navin{position:relative!important;isolation:isolate!important}.navin .hc-nav-indicator{position:absolute;left:0;top:4px;height:38px;width:0;border-radius:15px;background:linear-gradient(145deg,rgba(235,244,255,.82),rgba(247,252,255,.68));border:1px solid rgba(177,207,246,.62);box-shadow:0 5px 16px rgba(47,109,246,.09),inset 0 1px 0 rgba(255,255,255,.86);pointer-events:none;z-index:0;opacity:0;transform:translate3d(0,0,0);transition:transform .26s cubic-bezier(.2,.78,.22,1),width .22s cubic-bezier(.2,.78,.22,1),opacity .16s ease}.navin .hc-nav-indicator.on{opacity:1}.navin>button{position:relative;z-index:1;transition:transform .15s ease,color .2s ease,opacity .18s ease!important}.navin>button.on{background:transparent!important}

.filter,.rt-filterbar button,.toolbar button,.chip,.team-state{transition:transform .15s ease,opacity .18s ease,background-color .2s ease,border-color .2s ease,color .2s ease!important}.filter:active,.rt-filterbar button:active,.toolbar button:active{transform:scale(.975)}.filter.on,.rt-filterbar button.on{animation:hcFilterIn .19s cubic-bezier(.2,.72,.24,1) both}.chip.hc-status-chip,.team-state{animation:hcStateIn .17s ease both}
.notice-card.warning,.attention.red,.dangerbox{animation:hcWarningIn .22s ease both}.readonly-box,.notice-card.success{animation:hcSuccessIn .2s ease both}

.hc-toast-host{position:fixed;left:14px;right:14px;bottom:calc(88px + env(safe-area-inset-bottom));z-index:14000;display:grid;justify-items:center;gap:8px;pointer-events:none}.hc-toast{width:min(520px,100%);display:flex;align-items:flex-start;gap:10px;padding:11px 13px;border-radius:16px;background:rgba(24,34,50,.92);color:#fff;border:1px solid rgba(255,255,255,.14);box-shadow:0 14px 36px rgba(21,34,54,.21);backdrop-filter:blur(13px) saturate(130%);-webkit-backdrop-filter:blur(13px) saturate(130%);font-size:12.5px;font-weight:720;line-height:1.4;opacity:0;transform:translateY(9px) scale(.988);transition:opacity .19s ease,transform .23s cubic-bezier(.2,.72,.24,1)}.hc-toast.on{opacity:1;transform:none}.hc-toast.out{opacity:0;transform:translateY(5px) scale(.992)}.hc-toast:before{content:'✓';display:grid;place-items:center;flex:0 0 21px;width:21px;height:21px;border-radius:50%;background:#1ba568;color:#fff;font-size:11px;font-weight:900}.hc-toast.warn:before{content:'!';background:#e18a19}.hc-toast.error:before{content:'×';background:#d54a4a}.hc-toast.info:before{content:'i';background:#3476ff}

#main.hc-motion-ready>.hero,#main.hc-motion-ready>.section-title,#main.hc-motion-ready>.card,#main.hc-motion-ready>.grid,#main.hc-motion-ready>.search,#main.hc-motion-ready>.toolbar,#main.hc-motion-ready>.std-intro,#main.hc-motion-ready>.finance-grid{animation:hcScreenIn .24s cubic-bezier(.2,.72,.24,1) both}
#main.hc-motion-ready.hc-direction-back>.hero,#main.hc-motion-ready.hc-direction-back>.section-title,#main.hc-motion-ready.hc-direction-back>.card,#main.hc-motion-ready.hc-direction-back>.grid,#main.hc-motion-ready.hc-direction-back>.search,#main.hc-motion-ready.hc-direction-back>.toolbar,#main.hc-motion-ready.hc-direction-back>.std-intro,#main.hc-motion-ready.hc-direction-back>.finance-grid{animation-name:hcScreenBack!important}
#main.hc-motion-ready .metric,#main.hc-motion-ready .order-card,#main.hc-motion-ready .task-card,#main.hc-motion-ready .employee,#main.hc-motion-ready .notice-card{animation:hcCardIn .21s cubic-bezier(.2,.72,.24,1) both;will-change:auto}
#main.hc-motion-ready .order-card:nth-child(2),#main.hc-motion-ready .task-card:nth-child(2),#main.hc-motion-ready .notice-card:nth-child(2){animation-delay:18ms}#main.hc-motion-ready .order-card:nth-child(3),#main.hc-motion-ready .task-card:nth-child(3),#main.hc-motion-ready .notice-card:nth-child(3){animation-delay:36ms}#main.hc-motion-ready .order-card:nth-child(4),#main.hc-motion-ready .task-card:nth-child(4),#main.hc-motion-ready .notice-card:nth-child(4){animation-delay:54ms}#main.hc-motion-ready .order-card:nth-child(n+5),#main.hc-motion-ready .task-card:nth-child(n+5),#main.hc-motion-ready .notice-card:nth-child(n+5){animation-delay:72ms}

.rt-modal{animation:hcModalIn .19s ease both}.rt-sheet,.hc-access-sheet{animation:hcSheetIn .24s cubic-bezier(.2,.72,.24,1) both}.rt-modal.hc-motion-closing{animation:hcModalOut .17s ease both}.rt-modal.hc-motion-closing .rt-sheet{animation:hcSheetOut .17s ease both}.hc-viewer.on{animation:hcModalIn .17s ease both}.hc-viewer.on .hc-viewer-media{animation:hcViewerIn .21s cubic-bezier(.2,.72,.24,1) both}
.loading-media,.hc-media-skeleton{opacity:.72;transition:opacity .18s ease}.hc-media img,.hc-media video,.media img,.media video,.hc-viewer-media img,.hc-viewer-media video{opacity:.01;transform:scale(.995);transition:opacity .21s ease,transform .21s ease}.hc-media img.hc-media-loaded,.hc-media video.hc-media-loaded,.media img.hc-media-loaded,.media video.hc-media-loaded,.hc-viewer-media img.hc-media-loaded,.hc-viewer-media video.hc-media-loaded{opacity:1;transform:none}

details>summary{cursor:pointer;-webkit-tap-highlight-color:transparent;transition:transform .15s ease,opacity .18s ease}details>summary:active{transform:scale(.99)}details[open]>*:not(summary){animation:hcAccordionIn .19s ease both}

/* Correct sticky STAFF identity header: part of normal layout, never overlays content. */
.app{padding-top:0!important}
.top{position:sticky!important;top:0!important;left:auto!important;right:auto!important;width:auto!important;transform:none!important;z-index:110!important;margin:0!important;padding:10px 14px 9px!important;background:rgba(247,251,255,.94)!important;backdrop-filter:blur(15px) saturate(132%)!important;-webkit-backdrop-filter:blur(15px) saturate(132%)!important;border-bottom:1px solid rgba(190,209,234,.56)!important;box-shadow:0 5px 15px rgba(34,68,120,.035)!important}
.top .brand{gap:10px!important}.top .mark{width:40px!important;height:40px!important;border-radius:14px!important;font-size:15px!important;box-shadow:0 6px 16px rgba(47,109,246,.18)!important}.top .brand b{font-size:16px!important;line-height:1.12!important}.top .brand small{font-size:11.5px!important;margin-top:2px!important}:is(.back,.hc-v3-back,.hc-client-back,.hc-v4-back){position:sticky!important;top:8px!important;z-index:90!important;min-height:39px!important;margin:0 0 10px!important;padding:8px 11px!important;border:1px solid rgba(211,218,228,.9)!important;border-radius:14px!important;background:rgba(255,255,255,.9)!important;backdrop-filter:blur(16px)!important;-webkit-backdrop-filter:blur(16px)!important;box-shadow:0 5px 16px rgba(39,64,104,.08)!important}

/* Dense application-wide cell language. */
body{padding-bottom:calc(88px + env(safe-area-inset-bottom))!important}.main{padding:14px 12px 22px!important}.hero{border-radius:24px!important;padding:19px 18px!important;margin-bottom:13px!important;box-shadow:0 13px 32px rgba(43,102,239,.18)!important}.hero h1{font-size:25px!important;line-height:1.08!important}.hero p{font-size:13px!important}.section-title{margin:17px 2px 9px!important}.section-title h2{font-size:19px!important}.grid{gap:8px!important}.metric,.card{border-radius:17px!important;box-shadow:0 5px 17px rgba(44,72,112,.055)!important}.metric{padding:13px!important;min-height:88px!important}.metric strong{font-size:25px!important}.metric span{font-size:11px!important;margin-top:5px!important}.card{padding:11px 12px!important;margin-bottom:8px!important}.title{font-size:15px!important;line-height:1.24!important}.sub{font-size:12px!important;line-height:1.35!important;margin-top:2px!important}.meta{gap:5px!important;margin-top:7px!important}.chip{padding:4px 8px!important;font-size:10px!important}.avatar{width:42px!important;height:42px!important;border-radius:14px!important}.employee{gap:9px!important}.divider{margin:9px 0!important}.check,.payline{padding:8px 0!important}.notice-card{padding:10px 11px!important;border-radius:16px!important;margin-bottom:8px!important}.rt-priority-list .card,.task-card{padding:10px 11px!important;border-radius:17px!important;margin-bottom:8px!important}.hc-attention-card{gap:5px!important;padding:8px 9px!important;border-radius:12px!important}.hc-attention-reason{padding:6px 8px!important;border-radius:10px!important;font-size:10px!important;line-height:1.25!important}.hc-attention-address{font-size:11px!important;line-height:1.3!important}.hc-attention-client{font-size:12px!important}.rt-visit.hc-visit-card,.hc-access-person,.hc-access-form{border-radius:17px!important}.rt-visit.hc-visit-card{padding:11px!important}.search,.input,select,textarea,.money{min-height:44px!important;padding:10px 12px!important;border-radius:14px!important}.toolbar{gap:6px!important;padding-bottom:8px!important}.filter{min-height:38px!important;padding:8px 11px!important;font-size:11px!important}.notice,.readonly-box,.dangerbox{border-radius:15px!important;padding:10px 11px!important}

/* Compact order cells preserve number, client, status, date/time, service, address, team, amount and action. */
.order-card{padding:9px 10px!important;border-radius:16px!important;margin-bottom:7px!important}
.order-card .row{gap:6px!important;align-items:flex-start!important}.order-card .order-primary{min-width:0!important}.order-card .hc-order-heading{gap:5px!important;margin-bottom:1px!important;flex-wrap:nowrap!important}.order-card .hc-short-order{min-height:22px!important;padding:3px 7px!important;font-size:9.8px!important}.order-card .hc-card-client{font-size:14.5px!important;line-height:1.18!important}.order-card .row>.chip,.order-card .chip.hc-status-chip{flex:0 0 auto!important;font-size:9.5px!important;padding:4px 6px!important}.order-card .sub{font-size:11px!important;line-height:1.27!important;margin-top:2px!important}.order-card .order-address,.order-card .hc-human-address{font-size:11.5px!important;line-height:1.28!important;margin-top:4px!important;display:-webkit-box!important;-webkit-box-orient:vertical!important;-webkit-line-clamp:2;overflow:hidden!important}.order-card .compact-meta{gap:4px!important;margin-top:4px!important}.order-card .compact-meta span{font-size:9.4px!important;padding:3px 6px!important}.order-card .team-state{font-size:9.6px!important;padding:4px 7px!important;margin-top:4px!important;line-height:1.2!important}.order-card .btn.block{min-height:36px!important;padding:7px 10px!important;margin-top:6px!important;border-radius:12px!important;font-size:12px!important;box-shadow:0 4px 11px rgba(47,109,246,.09)!important}

/* Premium buttons: smaller, glass-aware and consistent. */
.btn{min-height:42px!important;padding:9px 13px!important;border-radius:15px!important;font-size:13px!important;font-weight:800!important;background:linear-gradient(145deg,#3378ff,#2464e8)!important;box-shadow:0 6px 15px rgba(47,109,246,.15),inset 0 1px 0 rgba(255,255,255,.18)!important;transition:transform .14s ease,opacity .18s ease,background-color .2s ease!important}.btn:active{transform:scale(.98)!important;opacity:.92}.btn.small{min-height:38px!important;padding:7px 10px!important;border-radius:13px!important;font-size:11.5px!important}.btn.secondary,.btn.soft{background:rgba(255,255,255,.72)!important;color:#245fae!important;border:1px solid rgba(185,207,236,.82)!important;box-shadow:0 4px 12px rgba(41,64,96,.045),inset 0 1px 0 rgba(255,255,255,.88)!important;backdrop-filter:blur(10px)!important;-webkit-backdrop-filter:blur(10px)!important}.btn.green{background:linear-gradient(145deg,#1ca96e,#12875a)!important}.btn.red{background:linear-gradient(145deg,#db5858,#be4242)!important}.hc-orders-refresh{min-height:34px!important;padding:6px 10px!important;border-radius:13px!important;background:rgba(255,255,255,.72)!important;box-shadow:0 4px 12px rgba(35,96,177,.055)!important;backdrop-filter:blur(10px)!important;-webkit-backdrop-filter:blur(10px)!important}

/* Pastel Standards cards with continuous depth during native swipe. */
#stdlist.hc-standards-track{display:flex!important;flex-wrap:nowrap!important;grid-template-columns:none!important;align-items:stretch!important;gap:10px!important;scroll-behavior:smooth!important;padding:6px 9vw 11px!important;scroll-padding-inline:9vw!important}
#stdlist.hc-standards-track .standard-card{display:flex!important;flex-direction:column!important;flex:0 0 clamp(270px,80vw,334px)!important;width:clamp(270px,80vw,334px)!important;min-width:clamp(270px,80vw,334px)!important;max-width:334px!important;height:auto!important;min-height:206px!important;box-sizing:border-box!important;padding:15px 15px 14px!important;border-radius:21px!important;opacity:var(--hc-std-opacity,.68)!important;transform:translateY(var(--hc-std-lift,5px)) scale(var(--hc-std-scale,.96))!important;transition:transform .18s cubic-bezier(.2,.78,.22,1),opacity .16s ease!important;box-shadow:0 9px 24px rgba(35,65,105,.075)!important;will-change:auto!important}
#stdlist.hc-standards-track .standard-card.hc-standard-active{box-shadow:0 11px 27px rgba(35,65,105,.10)!important}#stdlist.hc-standards-track .standard-card:active{transform:translateY(1px) scale(.985)!important}
#stdlist.hc-standards-track .standard-card.std-blue,#stdlist.hc-standards-track .standard-card.rt-std-blue{background:linear-gradient(155deg,#fbfdff 0%,#edf5ff 100%)!important;border-color:#b9d6fb!important}
#stdlist.hc-standards-track .standard-card.std-green,#stdlist.hc-standards-track .standard-card.rt-std-green{background:linear-gradient(155deg,#fbfffd 0%,#eaf8f1 100%)!important;border-color:#b9e3cd!important}
#stdlist.hc-standards-track .standard-card.std-orange,#stdlist.hc-standards-track .standard-card.rt-std-orange{background:linear-gradient(155deg,#fffdf9 0%,#fff1d9 100%)!important;border-color:#efd09a!important}
#stdlist.hc-standards-track .standard-card.std-red,#stdlist.hc-standards-track .standard-card.rt-std-red{background:linear-gradient(155deg,#fffdfd 0%,#ffedef 100%)!important;border-color:#efbfc4!important}
#stdlist.hc-standards-track .standard-card.std-purple,#stdlist.hc-standards-track .standard-card.rt-std-purple{background:linear-gradient(155deg,#fdfcff 0%,#f0ecff 100%)!important;border-color:#d3c7f3!important}
#stdlist.hc-standards-track .standard-card h3{font-size:18px!important;line-height:1.13!important;margin:9px 0 6px!important;letter-spacing:-.3px!important}#stdlist.hc-standards-track .standard-card p{font-size:12px!important;line-height:1.44!important;margin:0!important;display:-webkit-box!important;-webkit-box-orient:vertical!important;-webkit-line-clamp:5;overflow:hidden!important}#stdlist.hc-standards-track .hc-standard-top{min-height:24px!important}#stdlist.hc-standards-track .hc-standard-tag{padding:5px 8px!important;font-size:8.8px!important}.hc-std-controls{grid-template-columns:39px 1fr 39px!important;gap:8px!important;margin:1px 0 10px!important}.hc-std-arrow{width:39px!important;height:39px!important;font-size:21px!important;background:rgba(255,255,255,.74)!important;box-shadow:0 5px 15px rgba(32,69,118,.065)!important;backdrop-filter:blur(10px)!important;-webkit-backdrop-filter:blur(10px)!important}.hc-std-progress{gap:5px!important}.hc-std-count{font-size:10.5px!important}.hc-std-bar{height:3px!important}.hc-standard-panel{border-radius:26px 26px 0 0!important;padding:12px 14px calc(20px + env(safe-area-inset-bottom))!important}.hc-standard-sheet h2{font-size:23px!important;margin-top:14px!important}.hc-standard-sheet p{font-size:14px!important;line-height:1.55!important}.hc-standard-sheet-nav{gap:7px!important;margin-top:14px!important}.hc-standard-sheet-nav button{min-height:41px!important;border-radius:13px!important;background:rgba(255,255,255,.78)!important;box-shadow:0 4px 12px rgba(41,64,96,.04)!important}

/* Smaller Apple-like floating glass navigation. */
.nav{left:12px!important;right:12px!important;bottom:8px!important;padding:0 0 env(safe-area-inset-bottom)!important}.navin{min-height:70px!important;padding:5px 6px!important;gap:1px!important;border-radius:26px!important;background:rgba(255,255,255,.84)!important;border:1px solid rgba(210,222,239,.74)!important;box-shadow:0 13px 34px rgba(33,57,91,.14),inset 0 1px 0 rgba(255,255,255,.9)!important;backdrop-filter:blur(18px) saturate(135%)!important;-webkit-backdrop-filter:blur(18px) saturate(135%)!important}.nav button{min-height:58px!important;padding:3px 1px!important;border-radius:17px!important;font-size:9.8px!important;gap:1px!important}.nav button i{width:34px!important;height:34px!important;margin:0 auto!important;border-radius:12px!important;background:transparent!important;color:#66758b!important;font-size:18px!important;box-shadow:none!important}.nav button i svg{width:21px!important;height:21px!important}.nav button.on{color:#2266d8!important}.nav button.on i{background:transparent!important;color:#2266d8!important;box-shadow:none!important;transform:none!important}.nav button:active i,.nav button.on:active i{transform:scale(.94)!important}.sticky-actions{bottom:calc(88px + env(safe-area-inset-bottom))!important;padding-top:18px!important}

@keyframes hcScreenIn{from{opacity:0;transform:translateX(7px)}to{opacity:1;transform:none}}@keyframes hcScreenBack{from{opacity:0;transform:translateX(-7px)}to{opacity:1;transform:none}}@keyframes hcCardIn{from{opacity:0;transform:translateY(5px) scale(.995)}to{opacity:1;transform:none}}@keyframes hcFilterIn{from{opacity:.72;transform:scale(.97)}to{opacity:1;transform:none}}@keyframes hcStateIn{from{opacity:.55;transform:translateY(2px)}to{opacity:1;transform:none}}@keyframes hcWarningIn{from{opacity:.62;transform:translateY(3px)}to{opacity:1;transform:none}}@keyframes hcSuccessIn{from{opacity:.66;transform:translateY(3px)}to{opacity:1;transform:none}}@keyframes hcModalIn{from{opacity:0}to{opacity:1}}@keyframes hcModalOut{from{opacity:1}to{opacity:0}}@keyframes hcSheetIn{from{opacity:.76;transform:translateY(18px)}to{opacity:1;transform:none}}@keyframes hcSheetOut{from{opacity:1;transform:none}to{opacity:0;transform:translateY(14px)}}@keyframes hcViewerIn{from{opacity:.3;transform:scale(.986)}to{opacity:1;transform:none}}@keyframes hcAccordionIn{from{opacity:0;transform:translateY(-3px)}to{opacity:1;transform:none}}

@media(max-width:390px){.top{padding:9px 12px 8px!important}.top .mark{width:38px!important;height:38px!important}.main{padding-left:11px!important;padding-right:11px!important}.card,.task-card,.rt-priority-list .card{padding:10px!important}.order-card{padding:8px 9px!important}.order-card .hc-card-client{font-size:14px!important}#stdlist.hc-standards-track{padding-inline:9vw!important;scroll-padding-inline:9vw!important}#stdlist.hc-standards-track .standard-card{flex-basis:clamp(266px,82vw,316px)!important;width:clamp(266px,82vw,316px)!important;min-width:clamp(266px,82vw,316px)!important;min-height:198px!important;padding:14px!important}.nav{left:8px!important;right:8px!important;bottom:7px!important}.navin{min-height:68px!important;padding:4px 5px!important;border-radius:24px!important}.nav button{min-height:57px!important;font-size:9.2px!important}.nav button i{width:33px!important;height:33px!important}}
@media(prefers-reduced-motion:reduce){.hc-nav-indicator,.hc-toast,.filter,.rt-filterbar button,.toolbar button,.chip,.team-state,details>*,#main.hc-motion-ready>*,#main.hc-motion-ready .metric,#main.hc-motion-ready .order-card,#main.hc-motion-ready .task-card,#main.hc-motion-ready .employee,#main.hc-motion-ready .notice-card,.rt-modal,.rt-sheet,.hc-access-sheet,.hc-viewer.on,.hc-viewer.on .hc-viewer-media{animation:none!important;transition-duration:.01ms!important}.hc-media img,.hc-media video,.media img,.media video,.hc-viewer-media img,.hc-viewer-media video{opacity:1!important;transform:none!important;transition:none!important}#stdlist.hc-standards-track{scroll-behavior:auto!important}#stdlist.hc-standards-track .standard-card{transform:none!important;transition:none!important;opacity:1!important}}
</style>`;

const APP_MOTION_SCRIPT = String.raw`
<script>
(function(){
  var navFrame=0,dirTimer=0,toastSeq=0,stdFrame=0;
  function tg(){return window.Telegram&&window.Telegram.WebApp}
  function haptic(kind){try{var t=tg(),h=t&&t.HapticFeedback;if(!h)return;if(kind==='success'||kind==='warning'||kind==='error'){if(h.notificationOccurred)h.notificationOccurred(kind);return}if(h.impactOccurred)h.impactOccurred(kind||'light')}catch(e){}}
  function host(){var h=document.getElementById('hcToastHost');if(h)return h;h=document.createElement('div');h.id='hcToastHost';h.className='hc-toast-host';document.body.appendChild(h);return h}
  function kindOf(text){text=String(text||'').toLowerCase();if(/ошиб|не удалось|отмен|нельзя|нет доступа|не найден/.test(text))return'error';if(/вниман|проверь|сначала|дождитесь|нужно|точно/.test(text))return'warn';if(/сохран|готов|успеш|отправ|принят|обновл|заверш/.test(text))return'success';return'info'}
  window.__hcToast=function(message,type){var text=String(message==null?'':message).trim();if(!text)return;var k=type||kindOf(text),h=host(),el=document.createElement('div');el.className='hc-toast '+(k==='warning'?'warn':k);el.setAttribute('role','status');el.setAttribute('aria-live','polite');el.dataset.toast=String(++toastSeq);var span=document.createElement('span');span.textContent=text;el.appendChild(span);h.appendChild(el);haptic(k==='warn'?'warning':k==='info'?'light':k);requestAnimationFrame(function(){el.classList.add('on')});window.setTimeout(function(){el.classList.add('out');window.setTimeout(function(){el.remove()},230)},2600)};
  window.__hcCloseMotion=function(el){if(!el||el.classList.contains('hc-motion-closing'))return;el.classList.add('hc-motion-closing');window.setTimeout(function(){try{el.remove()}catch(e){}},185)};
  function indicator(){navFrame=0;var box=document.getElementById('navin');if(!box)return;var on=box.querySelector('button.on');if(!on)return;var ind=box.querySelector('.hc-nav-indicator');if(!ind){ind=document.createElement('div');ind.className='hc-nav-indicator';ind.setAttribute('aria-hidden','true');box.insertBefore(ind,box.firstChild)}var w=Math.max(38,on.offsetWidth-8);ind.style.width=w+'px';ind.style.transform='translate3d('+(on.offsetLeft+4)+'px,0,0)';ind.classList.add('on')}
  function queueIndicator(){if(navFrame)return;navFrame=requestAnimationFrame(indicator)}
  function markDirection(back){var main=document.getElementById('main');if(!main)return;main.classList.toggle('hc-direction-back',!!back);main.classList.toggle('hc-direction-forward',!back);if(dirTimer)clearTimeout(dirTimer);dirTimer=setTimeout(function(){main.classList.remove('hc-direction-back','hc-direction-forward')},380)}
  function tactile(target){if(!target)return;var hit=target.closest&&target.closest('.btn,.filter,.rt-filterbar button,#nav button,.rt-close,.hc-media,summary,.standard-card');if(!hit)return;haptic('light')}
  function mediaReady(target){if(!target||!target.matches)return;if(target.matches('.hc-media img,.hc-media video,.media img,.media video,.hc-viewer-media img,.hc-viewer-media video'))target.classList.add('hc-media-loaded')}
  function paintStandardDepth(list){stdFrame=0;if(!list||!document.documentElement.contains(list))return;var cards=[].slice.call(list.querySelectorAll('.standard-card'));if(!cards.length)return;var r=list.getBoundingClientRect(),center=r.left+r.width/2,reach=Math.max(1,r.width*.72);cards.forEach(function(card){var c=card.getBoundingClientRect(),d=Math.abs(c.left+c.width/2-center),p=Math.max(0,Math.min(1,1-d/reach)),scale=.94+.06*p,opacity=.62+.38*p,lift=6*(1-p);card.style.setProperty('--hc-std-scale',scale.toFixed(4));card.style.setProperty('--hc-std-opacity',opacity.toFixed(3));card.style.setProperty('--hc-std-lift',lift.toFixed(2)+'px')})}
  function queueStandardDepth(list){if(stdFrame)return;stdFrame=requestAnimationFrame(function(){paintStandardDepth(list||document.getElementById('stdlist'))})}
  function bindStandardDepth(){var list=document.getElementById('stdlist');if(!list)return;if(!list.dataset.hcDepthMotion){list.dataset.hcDepthMotion='1';list.addEventListener('scroll',function(){queueStandardDepth(list)},{passive:true})}queueStandardDepth(list)}
  document.addEventListener('pointerup',function(e){tactile(e.target)},{passive:true,capture:true});
  document.addEventListener('click',function(e){var b=e.target&&e.target.closest&&e.target.closest('.back');if(b)markDirection(true);else if(e.target&&e.target.closest&&e.target.closest('#nav button'))markDirection(false);queueIndicator()},true);
  document.addEventListener('load',function(e){mediaReady(e.target)},true);document.addEventListener('loadeddata',function(e){mediaReady(e.target)},true);
  document.addEventListener('hc:after-render',function(){queueIndicator();bindStandardDepth()},true);
  window.addEventListener('pageshow',function(){queueIndicator();bindStandardDepth()});
  window.addEventListener('resize',function(){queueIndicator();queueStandardDepth(document.getElementById('stdlist'))},{passive:true});
  queueIndicator();bindStandardDepth();
})();
</script>`;

export function applyStaffMotionSystem(app:string):string {
  let out=app;
  out=out.replace(
    "function M(html){document.getElementById('main').innerHTML=html;window.scrollTo(0,0)}",
    "function M(html){var main=document.getElementById('main');main.classList.remove('hc-motion-ready');main.innerHTML=html;if(!(window.__hcKeepScroll===true))window.scrollTo(0,0);window.__hcKeepScroll=false;Promise.resolve().then(function(){try{document.dispatchEvent(new CustomEvent('hc:after-render',{detail:{page:S&&S.page||''}}))}catch(e){var ev=document.createEvent('Event');ev.initEvent('hc:after-render',true,false);document.dispatchEvent(ev)}if(!document.documentElement.classList.contains('hc-ui-motion-gentle')&&!document.documentElement.classList.contains('hc-ui-motion-off'))requestAnimationFrame(function(){main.classList.add('hc-motion-ready')})})}"
  );
  // Route existing lightweight toast helpers to the native-looking in-app toast.
  out=out.replace(
    "function toast(x){try{T&&T.showAlert(String(x))}catch(e){alert(String(x))}}",
    "function toast(x){if(window.__hcToast)return window.__hcToast(String(x));try{T&&T.showAlert(String(x))}catch(e){alert(String(x))}}"
  );
  out=out.replaceAll(
    "if(tg&&tg.showAlert)return tg.showAlert(String(s))",
    "if(window.__hcToast)return window.__hcToast(String(s));if(tg&&tg.showAlert)return tg.showAlert(String(s))"
  );
  out=out.replaceAll(
    "if(t&&t.showAlert)return t.showAlert(String(s))",
    "if(window.__hcToast)return window.__hcToast(String(s));if(t&&t.showAlert)return t.showAlert(String(s))"
  );
  // Preserve synchronous app logic while giving the manual-order sheet a real reverse transition.
  out=out.replace(
    "document.getElementById('rtClose').onclick=function(){m.remove()};m.onclick=function(e){if(e.target===m)m.remove()}",
    "document.getElementById('rtClose').onclick=function(){window.__hcCloseMotion?window.__hcCloseMotion(m):m.remove()};m.onclick=function(e){if(e.target===m){window.__hcCloseMotion?window.__hcCloseMotion(m):m.remove()}}"
  );
  return out.replace('</head>', APP_MOTION_CSS + '</head>').replace('</body>', APP_MOTION_SCRIPT + '</body>');
}