import { STAFF_CURRENT_APP } from './staff-current-ui';

const OPS_CSS = String.raw`
<style>
.ops-parallel-note{margin:10px 0 13px;padding:12px 13px;border-radius:15px;background:#edf4ff;border:1px solid #bfd7ff;color:#315f9a;font-size:12px;line-height:1.5}.ops-parallel-note b{display:block;color:#174f98;font-size:14px;margin-bottom:2px}
.ops-report-card{background:#fff;border:1.5px solid #cbd9eb;border-radius:18px;padding:14px;margin-bottom:10px}.ops-report-card.started{border-color:#8fbaff;background:#f4f8ff}.ops-report-card.before_sent{border-color:#e8bd73;background:#fffaf0}.ops-report-card.done{border-color:#9ed8bc;background:#f4fcf8}.ops-report-card .ops-stage{font-size:11px;font-weight:850;border-radius:999px;padding:5px 9px;white-space:nowrap}.ops-report-card.started .ops-stage{background:#e5efff;color:#1769e0}.ops-report-card.before_sent .ops-stage{background:#fff0d1;color:#9b6108}.ops-report-card.done .ops-stage{background:#e2f6ec;color:#13764c}
.ops-upload-status{margin-top:8px;padding:10px 11px;border-radius:12px;background:#f5f8fc;border:1px solid #dce5f1;color:#5d6a7d;font-size:12px;line-height:1.4}.ops-upload-status.busy{background:#edf4ff;border-color:#bfd7ff;color:#315f9a}.ops-upload-status.ok{background:#eaf8f1;border-color:#bfe5d2;color:#176b48}.ops-upload-status.err{background:#fff0f0;border-color:#efc0c0;color:#963232}.ops-upload-status strong{font-weight:850}
.ops-time{margin:10px 0;padding:11px 12px;border-radius:14px;background:#f6f9fd;border:1px solid #dce5f1;color:#526074;font-size:12px}.ops-active-count{display:inline-flex;margin-top:8px;border-radius:999px;padding:5px 9px;background:#eef5ff;border:1px solid #c9dcfb;color:#1769e0;font-size:11px;font-weight:800}
</style>`;

const OPS_PATCH = String.raw`
/* Parallel reports patch — inside main STAFF closure */
var opsUploadLocks={};
function opsJobs(){var a=S.state&&Array.isArray(S.state.jobs)?S.state.jobs:[];if(!a.length&&S.state&&S.state.job)a=[S.state.job];return a.filter(Boolean)}
function opsJobForOrder(n){return opsJobs().find(function(j){return String(j.booking_order_number||'')===String(n)})||null}
function opsActiveJobs(){return opsJobs().filter(function(j){return j.stage!=='done'})}
function opsClock(ms){if(!ms)return'—';try{return new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(Number(ms)))}catch(e){return'—'}}
function opsDuration(j){var s=Number(j&&j.startedAt||0),e=Number(j&&j.finishedAt||0);if(!s)return 0;return Math.max(0,(e||Date.now())-s)}
function opsDurationText(ms){var m=Math.max(0,Math.floor(Number(ms||0)/60000)),h=Math.floor(m/60);return h?h+' ч '+(m%60)+' мин':m+' мин'}
function opsStageLabel(j){return j&&j.stage==='started'?'Фото ДО':j&&j.stage==='before_sent'?'Уборка / Фото ПОСЛЕ':j&&j.stage==='done'?'Отправлен':'Не начат'}
function opsClientId(file,index){try{return crypto.randomUUID()}catch(e){return Date.now()+'-'+index+'-'+String(file&&file.name||'file')+'-'+Math.random().toString(36).slice(2)}}
function opsKey(n,stage){return String(n)+'::'+String(stage)}
function opsStatusBox(){var up=document.getElementById('upload');if(!up)return null;var b=document.getElementById('opsUploadStatus');if(!b){b=document.createElement('div');b.id='opsUploadStatus';b.className='ops-upload-status';up.insertAdjacentElement('afterend',b)}return b}
function opsSetStatus(text,kind){var b=opsStatusBox();if(!b)return;b.className='ops-upload-status'+(kind?' '+kind:'');b.textContent=text}
async function opsDraftCount(stage,n){try{var x=await api('/api/staff/draft-count?stage='+encodeURIComponent(stage)+'&order_number='+encodeURIComponent(n));return Number(x.count||0)}catch(e){return 0}}
async function opsUploadFiles(stage,n,files,input){if(!files||!files.length)return;var key=opsKey(n,stage);if(opsUploadLocks[key])return toast('Загрузка уже идёт');opsUploadLocks[key]=true;input.disabled=true;var send=document.getElementById('sendstage');if(send)send.disabled=true;var ids=[].slice.call(files).map(opsClientId),saved=0;try{for(var i=0;i<files.length;i++){opsSetStatus('Загружаем '+(i+1)+' из '+files.length+'…','busy');var last=null;for(var attempt=0;attempt<3;attempt++){try{var fd=new FormData();fd.append('stage',stage);fd.append('order_number',n);fd.append('client_id',ids[i]);fd.append('media',files[i]);await api('/api/media/draft',{method:'POST',body:fd});last=null;break}catch(e){last=e;if(attempt<2)await new Promise(function(r){setTimeout(r,450*(attempt+1))})}}if(last)throw last;saved++;var count=await opsDraftCount(stage,n);opsSetStatus('Сохранено файлов: '+count+'. Можно добавить ещё.','ok')}}catch(e){opsSetStatus('Сохранено '+saved+' из '+files.length+'. '+e.message,'err');toast(e.message)}finally{opsUploadLocks[key]=false;input.disabled=false;input.value='';if(send)send.disabled=false;var total=await opsDraftCount(stage,n);opsSetStatus(total?'Сохранено файлов: '+total+'. '+(total>=2?'Этап можно отправлять.':'Нужно минимум 2.'):'Добавьте минимум 2 фото или видео.',total>=2?'ok':'')}}
async function opsRefresh(){var a=await Promise.all([api('/api/state'),api('/api/staff/orders')]);S.state=a[0];S.orders=a[1].orders||[];return a[0]}
function opsTiming(j){if(!j||!j.startedAt)return'';return '<div class="ops-time">Начало: <b>'+opsClock(j.startedAt)+'</b>'+(j.finishedAt?' · Завершение: <b>'+opsClock(j.finishedAt)+'</b>':'')+' · '+(j.finishedAt?'Итого: ':'Идёт: ')+'<b>'+opsDurationText(opsDuration(j))+'</b></div>'}

photoStage=function(o,stage){var n=String(o.order_number||'');return '<div class="title">Фото ДО</div><div class="sub">Фото этого объекта сохраняются отдельно от остальных активных уборок. Добавьте минимум 2 фото/видео.</div><input id="upload" data-hc-stable="1" data-stage="'+stage+'" data-order="'+H(n)+'" class="input" type="file" accept="image/*,video/*" multiple><textarea id="defect" placeholder="Дефекты / замечания до уборки"></textarea><button id="sendstage" data-hc-stable="1" data-stage="'+stage+'" data-order="'+H(n)+'" class="btn block">Отправить фото ДО</button>'};
checklistStage=function(o,m){var c=m.checklist||[],n=String(o.order_number||'');return '<div class="title">Чек-лист уборки</div><div class="sub">Отметьте выполненные пункты именно по этому объекту.</div>'+c.map(function(x,i){return '<label class="check"><input type="checkbox" data-check="'+i+'" '+(x.done?'checked':'')+'><span>'+H(x.label)+'</span></label>'}).join('')+'<div class="divider"></div><div class="title">Фото ПОСЛЕ</div><div class="sub">Можно добавлять фото несколькими выборами — они не смешаются с другими заказами.</div><input id="upload" data-hc-stable="1" data-stage="after" data-order="'+H(n)+'" class="input" type="file" accept="image/*,video/*" multiple><button id="sendstage" data-hc-stable="1" data-stage="after" data-order="'+H(n)+'" class="btn green block">Отправить ПОСЛЕ и завершить</button>'};

taskActions=function(o,m,id,job){if(o.status==='CANCELLED')return '<div class="readonly-box" style="background:#fff0f0;border-color:#efc0c0;color:#963232"><b>Заказ отменён</b>Действия недоступны.</div>';if(o.status==='COMPLETED'||Number(m.verified_at||0)>0)return '<div class="readonly-box"><b>✅ Работа принята руководителем</b>Заказ закрыт. Отчёт доступен только для просмотра.</div>';if(!(m.accepted&&m.accepted[id]))return '<div class="title">Новое задание</div><div class="sub">Подтвердите, что берёте эту уборку.</div><button class="btn block" data-act="accept">Принять задание</button>';if(!(m.confirmed&&m.confirmed[id]))return '<div class="title">Задание принято</div><div class="sub">Перед выходом подтвердите, что всё в силе.</div><button class="btn block" data-act="confirm">Подтвердить выход</button>';if(!job&&!(m.started&&m.started[id]))return '<div class="title">Можно начинать</div><div class="sub">Этот фотоотчёт будет независимым от других ваших активных заказов.</div><button class="btn green block" data-act="start" data-hc-confirm="1">Начать уборку</button>';if(job&&job.stage==='started')return photoStage(o,'before');if(job&&job.stage==='before_sent')return checklistStage(o,m);if(job&&job.stage==='done')return '<div class="title">Работа завершена</div><div class="sub">Фотоотчёт отправлен. Ожидайте проверки руководителя.</div><span class="chip orange">Ожидает проверки</span>';if(m.started&&m.started[id])return '<div class="sub">Фотоотчёт восстанавливается. Обновите задание через несколько секунд.</div>';return '<div class="sub">Состояние задания обновляется.</div>'};

bindTask=function(o,m,id,job){document.querySelectorAll('[data-act]').forEach(function(b){b.onclick=async function(){var action=String(b.dataset.act||'');if(action==='start'&&!confirm('Точно начать уборку и фотоотчёт? Время этой уборки начнёт считаться сейчас. Можно одновременно вести другие назначенные вам фотоотчёты.'))return;var old=b.textContent;try{b.disabled=true;b.textContent='Сохраняем…';await api('/api/staff/order/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({order_number:o.order_number,action:action})});await opsRefresh();taskDetail(o.order_number)}catch(e){b.disabled=false;b.textContent=old;toast(e.message)}}});var up=document.getElementById('upload');if(up){var stage=String(up.dataset.stage||''),n=String(up.dataset.order||o.order_number);up.onchange=function(){opsUploadFiles(stage,n,up.files,up)};opsDraftCount(stage,n).then(function(count){opsSetStatus(count?'Уже сохранено файлов: '+count+'. '+(count>=2?'Можно отправлять этап.':'Нужно минимум 2.'):'Добавьте минимум 2 фото или видео.',count>=2?'ok':'')})}var send=document.getElementById('sendstage');if(send)send.onclick=async function(){var stage=String(send.dataset.stage||''),n=String(send.dataset.order||o.order_number),key=opsKey(n,stage);if(opsUploadLocks[key])return toast('Дождитесь окончания загрузки файлов');var count=await opsDraftCount(stage,n);if(count<2)return toast('Сначала добавьте минимум 2 фото или видео');var question=stage==='after'?'Точно отправить фото ПОСЛЕ и завершить отчёт по заказу '+n+'?':'Отправить фото ДО по заказу '+n+' и продолжить уборку?';if(!confirm(question))return;var old=send.textContent;try{send.disabled=true;send.textContent=stage==='after'?'Завершаем отчёт…':'Сохраняем Фото ДО…';await api(stage==='after'?'/api/after':'/api/before',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({order_number:n,defect_note:(document.getElementById('defect')||{}).value||''})});await opsRefresh();toast(stage==='after'?'Фотоотчёт отправлен руководителю':'Фото ДО сохранены');taskDetail(n)}catch(e){send.disabled=false;send.textContent=old;toast(e.message)}};document.querySelectorAll('[data-check]').forEach(function(c){c.onchange=async function(){var idx=Number(c.dataset.check),prev=!c.checked;try{c.disabled=true;await api('/api/staff/checklist',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({order_number:o.order_number,index:idx,done:c.checked})});if(m.checklist&&m.checklist[idx])m.checklist[idx].done=c.checked}catch(e){c.checked=prev;toast(e.message)}finally{c.disabled=false}}})};

taskDetail=async function(n){try{var a=await Promise.all([api('/api/staff/order?number='+encodeURIComponent(n)),api('/api/state')]),o=a[0].order,Sstate=a[1];S.state=Sstate;var m=o.staff||{},id=Number(S.state&&S.state.employee&&S.state.employee.id||0),job=opsJobForOrder(n),accepted=m.accepted&&m.accepted[id],confirmed=m.confirmed&&m.confirmed[id],started=!!job||m.started&&m.started[id],active=opsActiveJobs().length;M('<button class="back" id="tback">← Мои задания</button>'+(active>1?'<div class="ops-parallel-note"><b>Одновременно активны '+active+' фотоотчёта</b>Фото, чек-лист и время каждого заказа хранятся отдельно. Можно свободно переключаться между заданиями.</div>':'')+'<div class="card"><div class="title">'+H(o.order_number)+' · '+H(o.service_name||'Уборка')+'</div><div class="sub">'+dmy(o.date)+' · '+H(o.time||'—')+' · '+H(o.area||0)+' м²</div><div class="divider"></div><div class="kv"><div>Адрес</div><div>'+H([o.city,o.address,o.apartment].filter(Boolean).join(', '))+'</div><div>Клиент</div><div>'+H(o.customer_name||'Клиент')+'</div><div>Доп. услуги</div><div>'+H((o.addon_names||[]).join(', ')||'—')+'</div></div></div><div class="stagebar"><div class="stage '+(accepted?'done':'')+'"></div><div class="stage '+(confirmed?'done':'')+'"></div><div class="stage '+(started?'done':'')+'"></div></div>'+opsTiming(job)+'<div class="card" id="actions">'+taskActions(o,m,id,job)+'</div>');document.getElementById('tback').onclick=function(){go('tasks')};bindTask(o,m,id,job)}catch(e){toast(e.message)}};

workerPhotos=async function(){try{S.state=await api('/api/state')}catch(e){}var jobs=opsJobs().slice().sort(function(a,b){var aa=a.stage==='done'?1:0,bb=b.stage==='done'?1:0;if(aa!==bb)return aa-bb;return Number(b.updatedAt||b.startedAt||0)-Number(a.updatedAt||a.startedAt||0)});var visible=jobs.filter(function(j){return j.stage!=='done'});var recent=jobs.filter(function(j){return j.stage==='done'}).slice(0,5);var all=visible.concat(recent);M('<div class="section-title"><h2>Фотоотчёты</h2><span>'+visible.length+' активных</span></div>'+(visible.length>1?'<div class="ops-parallel-note"><b>Параллельные отчёты включены</b>Можно вести несколько уборок одновременно. Материалы каждого заказа изолированы.</div>':'')+(all.length?all.map(function(j){var cls=H(j.stage||'started'),n=H(j.booking_order_number||'');return '<div class="ops-report-card '+cls+'"><div class="row"><div class="grow"><div class="title">'+n+'</div><div class="sub">'+H(j.address||j.customer||'')+'</div></div><span class="ops-stage">'+H(opsStageLabel(j))+'</span></div>'+opsTiming(j)+'<div class="meta"><span class="chip">ДО '+Number(j.beforeCount||0)+'</span><span class="chip">ПОСЛЕ '+Number(j.afterCount||0)+'</span></div><button class="btn soft block" data-ops-task="'+n+'">Открыть этот заказ</button></div>'}).join(''):'<div class="card empty">Активных фотоотчётов пока нет</div>'));document.querySelectorAll('[data-ops-task]').forEach(function(b){b.onclick=function(){taskDetail(b.dataset.opsTask)}})};

workerHome=function(){if(S.me&&S.me.profile&&S.me.profile.admitted===false)return onboarding();var activeReports=opsActiveJobs(),orders=S.orders.filter(function(x){return['COMPLETED','CANCELLED'].indexOf(x.status)<0}),o=orders.find(function(x){var j=opsJobForOrder(x.order_number);return !j||j.stage!=='done'})||orders[0];M('<div class="hero"><h1>'+(o?'Ближайшая уборка':'Новых заданий пока нет')+'</h1><p>'+(o?dmy(o.date)+' · '+H(o.time||'—')+' · '+H([o.city,o.address].filter(Boolean).join(', ')):'Ожидайте новое назначение от руководителя.')+'</p></div>'+(activeReports.length?'<div class="ops-parallel-note"><b>Активных фотоотчётов: '+activeReports.length+'</b>'+(activeReports.length>1?'Можно переключаться между ними без потери фото и чек-листа.':'Фотоотчёт сохраняется автоматически.')+'<button id="opsOpenReports" class="btn soft block">Открыть фотоотчёты</button></div>':'')+(o?'<div class="card"><div class="title">'+H(o.order_number)+' · '+H(o.service_name||'Уборка')+'</div><div class="sub">'+H(o.area||0)+' м² · '+H([o.city,o.address,o.apartment].filter(Boolean).join(', '))+'</div><button class="btn block" data-task="'+H(o.order_number)+'">Открыть задание</button></div>':'<div class="card empty">Назначенных активных заказов нет</div>')+'<div class="card"><div class="title">Стандарты HOUSE CLEANING</div><div class="sub">Регламент, химия, поверхности, фотоотчёты и общение с клиентом.</div><button id="cheat" class="btn soft block">Открыть стандарты</button></div>');document.querySelectorAll('[data-task]').forEach(function(b){b.onclick=function(){taskDetail(b.dataset.task)}});var r=document.getElementById('opsOpenReports');if(r)r.onclick=function(){S.page='photos';nav();workerPhotos()};var c=document.getElementById('cheat');if(c)c.onclick=function(){S.page='standards';nav();standards()}};
`;

const anchor = 'boot();\n})();\n</script>';
const patched = STAFF_CURRENT_APP.replace(anchor, OPS_PATCH + '\nboot();\n})();\n</script>');
export const STAFF_OPERATIONS_APP = patched.replace('</head>', OPS_CSS + '</head>');
