export const STAFF_COMMAND_V4_BUILD='staff-command-v4-2026-09-17-a';

const CSS=String.raw`
<style id="hcCommandV4Style">
html.hc-command-v4{--v4-ink:#101114;--v4-muted:#7c8088;--v4-card:#fff;--v4-soft:#f0f1f3;--v4-line:#e5e6e9;--v4-blue:#2474f2;--v4-red:#d84b4b;--v4-green:#1c9963}
html.hc-command-v4 .hc-v3-command{margin-bottom:10px!important}
html.hc-command-v4 .hc-v3-command-head strong{font-size:29px!important;letter-spacing:-1px!important}
html.hc-command-v4 .hc-v4-quick-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}
html.hc-command-v4 .hc-v4-quick{appearance:none;border:0;background:#fff;border-radius:21px;min-height:116px;padding:12px 7px 10px;display:grid;grid-template-rows:1fr auto;place-items:center;color:#17191d;box-shadow:none}
html.hc-command-v4 .hc-v4-quick:active{transform:scale(.975)}
html.hc-command-v4 .hc-v4-quick i{display:grid;place-items:center;width:46px;height:46px;border-radius:16px;background:#f0f1f3;color:#323943;font-style:normal}
html.hc-command-v4 .hc-v4-quick[data-v4-go="notify"] i{background:#fff1cf;color:#8a6200}
html.hc-command-v4 .hc-v4-quick svg{width:23px;height:23px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}
html.hc-command-v4 .hc-v4-quick b{font-size:11px;font-weight:850}
html.hc-command-v4 #main[data-hc-catalog-page="overview"]>.grid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}
html.hc-command-v4 #main[data-hc-catalog-page="overview"]>.grid>.metric{position:relative;min-height:92px!important;padding:13px 13px 12px!important;border:0!important;border-radius:22px!important;background:#fff!important;cursor:pointer}
html.hc-command-v4 #main[data-hc-catalog-page="overview"]>.grid>.metric:after{content:'›';position:absolute;right:13px;top:12px;color:#c0c3c8;font-size:22px;font-weight:400}
html.hc-command-v4 #main[data-hc-catalog-page="overview"]>.grid>.metric strong{font-size:28px!important;letter-spacing:-1px!important}
html.hc-command-v4 #main[data-hc-catalog-page="overview"]>.grid>.metric span{font-size:10.5px!important;color:#777c84!important;max-width:80%;line-height:1.25!important}
html.hc-command-v4 #main[data-hc-catalog-page="overview"]>.grid>.metric small{display:block;margin-top:7px;font-size:8.8px;color:#a0a4aa;font-weight:750}
html.hc-command-v4 .hc-v4-attention{position:relative;border:0!important;border-radius:21px!important;background:#fff!important;padding:11px 39px 11px 12px!important;margin-bottom:7px!important;box-shadow:none!important;min-height:70px}
html.hc-command-v4 .hc-v4-attention:after{content:'›';position:absolute;right:14px;top:50%;transform:translateY(-50%);font-size:27px;color:#b8bbc1}
html.hc-command-v4 .hc-v4-attention[data-order],html.hc-command-v4 .hc-v4-attention[data-v4-target]{cursor:pointer}
html.hc-command-v4 .hc-v4-attention-top{display:flex;align-items:center;gap:7px;margin-bottom:4px}.hc-v4-attention-dot{width:22px;height:22px;border-radius:9px;display:grid;place-items:center;background:#fff0f0;color:#c63b3b;font-size:12px;font-weight:900;flex:none}
html.hc-command-v4 .hc-v4-attention strong{font-size:12px;line-height:1.25;color:#202329}.hc-v4-attention p{margin:0;color:#7a7f87;font-size:10.5px;line-height:1.3}
html.hc-command-v4 .hc-v4-section-link{appearance:none;border:0;background:transparent;color:#8a8f97;font-size:10px;font-weight:800;padding:5px 0}
html.hc-command-v4 .hc-v4-upcoming-head{display:flex;align-items:end;justify-content:space-between;margin:18px 2px 9px}.hc-v4-upcoming-head h2{margin:0;font-size:24px;letter-spacing:-.65px}.hc-v4-upcoming-head span{font-size:10px;color:#92969d}
html.hc-command-v4 .hc-v4-order-state{display:flex;gap:6px;overflow-x:auto;scrollbar-width:none;margin:0 0 9px}.hc-v4-order-state::-webkit-scrollbar{display:none}.hc-v4-order-state span{white-space:nowrap;background:#fff;border-radius:999px;padding:6px 9px;font-size:9px;color:#747981;font-weight:780}.hc-v4-order-state span b{color:#17191d;margin-right:3px}
html.hc-command-v4 .hc-v4-template-wrap{display:grid;gap:9px;margin-top:13px}.hc-v4-template{background:#fff;border-radius:18px;padding:12px}.hc-v4-template-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.hc-v4-template-head strong{font-size:12.5px}.hc-v4-template-head button{appearance:none;border:0;background:#f0f1f3;border-radius:10px;padding:6px 8px;font-size:9px;font-weight:800;color:#60656d}.hc-v4-template p{margin:3px 0 8px;color:#8a8f97;font-size:9.5px;line-height:1.3}.hc-v4-template textarea{width:100%;min-height:108px;border:0!important;background:#f5f5f6!important;border-radius:13px!important;padding:10px!important;font-size:11px!important;line-height:1.4!important}.hc-v4-template-vars{margin-top:6px;color:#9a9ea5;font-size:8.5px;line-height:1.4}.hc-v4-template-save{width:100%;margin-top:8px;min-height:38px;border:0;border-radius:13px;background:#111820;color:#fff;font-weight:850;font-size:10.5px}
html.hc-command-v4 .hc-v4-photo-page{display:grid;gap:8px}.hc-v4-photo-head{display:flex;align-items:end;justify-content:space-between;margin:3px 2px 6px}.hc-v4-photo-head h2{margin:0;font-size:29px;letter-spacing:-1px}.hc-v4-photo-head span{font-size:10px;color:#8d9299}.hc-v4-photo-tabs{display:flex;gap:6px;overflow:auto;scrollbar-width:none}.hc-v4-photo-tabs button{appearance:none;border:0;border-radius:12px;background:#fff;padding:8px 10px;font-size:9.5px;font-weight:800;color:#747981;white-space:nowrap}.hc-v4-photo-tabs button.on{background:#111820;color:#fff}.hc-v4-photo-card{appearance:none;width:100%;position:relative;text-align:left;border:0;background:#fff;border-radius:21px;padding:12px 42px 12px 12px;color:#17191d;min-height:78px}.hc-v4-photo-card:after{content:'›';position:absolute;right:15px;top:50%;transform:translateY(-50%);font-size:27px;color:#b6bac0}.hc-v4-photo-card strong{display:block;font-size:13px}.hc-v4-photo-card p{margin:4px 0 0;color:#747981;font-size:10.5px;line-height:1.32}.hc-v4-photo-card .hc-v4-photo-meta{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.hc-v4-photo-card .hc-v4-photo-meta span{background:#f1f2f4;border-radius:999px;padding:4px 6px;font-size:8.5px;color:#676c73}.hc-v4-photo-card .hc-v4-photo-meta .ready{background:#eaf8f1;color:#137f51}.hc-v4-photo-card .hc-v4-photo-meta .review{background:#fff1dc;color:#9b6200}
html.hc-command-v4 .hc-v4-photo-detail{display:grid;gap:9px}.hc-v4-back{appearance:none;border:0;background:#fff;border-radius:13px;min-height:38px;padding:8px 11px;font-weight:850;color:#303640;justify-self:start}.hc-v4-photo-summary{background:#fff;border-radius:22px;padding:13px}.hc-v4-photo-summary strong{display:block;font-size:15px}.hc-v4-photo-summary p{margin:4px 0 0;font-size:10.5px;color:#747981;line-height:1.35}.hc-v4-photo-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.hc-v4-photo-thumb{border:0;background:#e7e8ea;border-radius:15px;aspect-ratio:1;overflow:hidden;padding:0}.hc-v4-photo-thumb img,.hc-v4-photo-thumb video{width:100%;height:100%;object-fit:cover;display:block}.hc-v4-photo-empty{padding:24px 14px;text-align:center;background:#fff;border-radius:20px;color:#8a8f97;font-size:11px}
html.hc-command-v4 .hc-v4-media-view{position:fixed;inset:0;z-index:26000;background:rgba(8,10,14,.97);display:none;align-items:center;justify-content:center;padding:70px 12px 24px}.hc-v4-media-view.on{display:flex}.hc-v4-media-view img,.hc-v4-media-view video{max-width:100%;max-height:82vh;border-radius:14px}.hc-v4-media-close{position:absolute;top:calc(14px + env(safe-area-inset-top));right:14px;width:42px;height:42px;border:0;border-radius:50%;background:#fff;color:#111;font-size:23px}
html.hc-command-v4 .hc-v4-orders-restoring{opacity:.65;pointer-events:none}
@media(max-width:390px){html.hc-command-v4 .hc-v4-quick{min-height:105px}.hc-v4-photo-grid{grid-template-columns:repeat(3,1fr)}}
@media(prefers-reduced-motion:reduce){html.hc-command-v4 .hc-v4-quick:active{transform:none}}
</style>`;

const JS=String.raw`
<script id="hcCommandV4Script">
(function(){
 if(window.__hcCommandV4)return;window.__hcCommandV4=true;document.documentElement.classList.add('hc-command-v4');
 var queued=false,state=null,photoFilter='all',photoJobs=null,templates=null,defaults=null,mediaUrls=[],viewState={};
 try{viewState=JSON.parse(sessionStorage.getItem('hc:v4:view')||'{}')||{}}catch(e){viewState={}}
 function tg(){return window.Telegram&&window.Telegram.WebApp}
 function headers(){var t=tg(),h={'content-type':'application/json'},launch=new URLSearchParams(location.search).get('launch')||'';if(launch)h['X-App-Launch-Token']=launch;if(t&&t.initData)h['X-Telegram-Init-Data']=t.initData;return h}
 async function api(path,opt){opt=opt||{};var r=await fetch(path,{method:opt.method||'GET',headers:headers(),body:opt.body?JSON.stringify(opt.body):undefined,cache:'no-store'}),ct=r.headers.get('content-type')||'',x=ct.indexOf('json')>=0?await r.json():await r.text();if(!r.ok||x&&x.ok===false)throw Error(x&&x.error||x||'Ошибка');return x}
 function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
 function toast(s,k){if(window.__hcToast)return window.__hcToast(s,k);try{tg()&&tg().showAlert(s)}catch(e){}}
 function activeTab(){var b=document.querySelector('#nav button.on');return b&&b.dataset.n||''}
 function save(){try{sessionStorage.setItem('hc:v4:view',JSON.stringify(viewState))}catch(e){}}
 function capture(tab){tab=tab||activeTab();if(!tab)return;var main=document.getElementById('main');var v={scroll:window.scrollY||0};if(tab==='orders'&&main){var q=main.querySelector('.search');if(q)v.q=q.value||'';var f=main.querySelector('.filter.on');if(f)v.filter=(f.textContent||'').trim()}viewState[tab]=v;save()}
 function restore(tab){var v=viewState[tab];if(!v)return;requestAnimationFrame(function(){requestAnimationFrame(function(){var main=document.getElementById('main');if(tab==='orders'&&main){if(v.q){var q=main.querySelector('.search');if(q){q.value=v.q;q.dispatchEvent(new Event('input',{bubbles:true}))}}if(v.filter){var fs=[].slice.call(main.querySelectorAll('.filter'));var f=fs.find(function(x){return String(x.textContent||'').trim()===v.filter});if(f&&!f.classList.contains('on'))f.click()}}window.scrollTo(0,Number(v.scroll||0))})})}
 function navTo(k,restoreAfter){var b=document.querySelector('#nav button[data-n="'+k+'"]');if(!b)return false;b.click();if(restoreAfter)restore(k);return true}
 function svg(k){var m={orders:'<svg viewBox="0 0 24 24"><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>',employees:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3.5 20a5.5 5.5 0 0 1 11 0"/><circle cx="17" cy="9" r="2"/><path d="M15.5 14.5A4.5 4.5 0 0 1 21 19"/></svg>',photos:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m5 17 4-4 3 3 2-2 5 3"/></svg>',notify:'<svg viewBox="0 0 24 24"><path d="M18 8a6 6 0 1 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></svg>'};return m[k]||''}
 function decorateOverview(main){
   var cmd=main.querySelector('.hc-v3-command');if(cmd&&!cmd.dataset.v4){cmd.dataset.v4='1';cmd.innerHTML='<div class="hc-v3-command-head"><strong>Сегодня</strong><span>Быстрые действия</span></div><div class="hc-v4-quick-grid"><button class="hc-v4-quick" data-v4-go="orders"><i>'+svg('orders')+'</i><b>Заявки</b></button><button class="hc-v4-quick" data-v4-go="employees"><i>'+svg('employees')+'</i><b>Команда</b></button><button class="hc-v4-quick" data-v4-go="photos"><i>'+svg('photos')+'</i><b>Фото</b></button><button class="hc-v4-quick" data-v4-go="notify"><i>'+svg('notify')+'</i><b>Оповещения</b></button></div>'}
   var metrics=[].slice.call(main.querySelectorAll(':scope>.grid>.metric'));metrics.forEach(function(m,i){m.dataset.v4Metric=i===0?'orders':i===1?'unassigned':i===2?'employees':'work';if(!m.querySelector('small')){var x=document.createElement('small');x.textContent=i===0?'Открыть график':i===1?'Назначить команду':i===2?'Управление командой':'Открыть активные';m.appendChild(x)}});
   var attTitle=[].slice.call(main.querySelectorAll('.section-title h2')).find(function(x){return/Требует внимания/i.test(x.textContent||'')});if(attTitle){var section=attTitle.closest('.section-title'),node=section&&section.nextElementSibling;while(node&&!node.classList.contains('section-title')){var next=node.nextElementSibling;if(node.classList.contains('attention')&&!node.dataset.v4){var btn=node.querySelector('[data-order]'),text=(node.textContent||'').replace(/Открыть/g,'').trim(),order=btn&&btn.getAttribute('data-order')||'';node.dataset.v4='1';node.className='hc-v4-attention';if(order)node.dataset.order=order;else if(/Фотоотчёт/i.test(text))node.dataset.v4Target='photos';node.innerHTML='<div class="hc-v4-attention-top"><span class="hc-v4-attention-dot">!</span><strong>'+esc(order?'Требует действия':/Фотоотчёт/i.test(text)?'Проверить фото':'Проверка')+'</strong></div><p>'+esc(text)+'</p>'}node=next}}
   var heads=[].slice.call(main.querySelectorAll('.section-title h2'));var pr=heads.find(function(x){return/Заказы в приоритете/i.test(x.textContent||'')});if(pr){pr.textContent='Ближайшие уборки';var st=pr.parentElement&&pr.parentElement.querySelector('span');if(st)st.textContent='сначала то, что требует действия'}
 }
 function decorateOrders(main){if(main.dataset.v4Orders==='1')return;main.dataset.v4Orders='1';var h=main.querySelector('.section-title h2');if(h)h.textContent='Заявки';var s=main.querySelector('.hc-v3-order-summary');if(s)s.classList.add('hc-v4-order-state')}
 async function ensureState(){if(state)return state;try{state=await api('/api/state')}catch(e){state={}}return state}
 async function openTemplates(){try{var x=await api('/api/staff/notification-templates');templates=x.templates||{};defaults=x.defaults||null;return x}catch(e){throw e}}
 var templateRows=[['new_order','Новая заявка','Сообщение руководителю при новом заказе'],['order_changed','Изменение заказа','Когда меняются дата, время, адрес или услуга'],['order_cancelled','Отмена заказа','Сообщение руководителю при отмене'],['finance_changes','Реквизиты сотрудника','Когда сотрудник меняет реквизиты'],['broadcast','Рассылка','Обрамление ручной рассылки']];
 async function injectTemplates(){var pane=document.getElementById('hcV3NotifyPane');if(!pane||!document.querySelector('[data-v3-tab="settings"].on'))return;if(pane.querySelector('.hc-v4-template-wrap'))return;try{var x=await openTemplates(),wrap=document.createElement('div');wrap.className='hc-v4-template-wrap';wrap.innerHTML='<div class="hc-v3-note"><b>Тексты сообщений</b><br>Можно менять шаблоны Telegram. Переменные в фигурных скобках подставляются автоматически. Уведомление о дефекте с фото пока использует системную подпись, чтобы не нарушить передачу фото.</div>'+templateRows.map(function(r){var vars=(x.placeholders&&x.placeholders[r[0]]||[]).map(function(v){return'{'+v+'}'}).join(' · ');return'<div class="hc-v4-template" data-v4-template="'+r[0]+'"><div class="hc-v4-template-head"><strong>'+esc(r[1])+'</strong><button data-v4-reset="'+r[0]+'">Сбросить</button></div><p>'+esc(r[2])+'</p><textarea data-v4-text="'+r[0]+'">'+esc((x.templates||{})[r[0]]||'')+'</textarea><div class="hc-v4-template-vars">'+esc(vars)+'</div><button class="hc-v4-template-save" data-v4-save="'+r[0]+'">Сохранить текст</button></div>'}).join('');pane.appendChild(wrap)}catch(e){toast(e.message,'error')}}
 async function saveTemplate(key,reset){var x=await api('/api/staff/notification-templates');var all=Object.assign({},x.templates||{});if(reset){var d=await api('/api/staff/notification-templates?defaults=1').catch(function(){return null});if(d&&d.templates&&d.templates[key])all[key]=d.templates[key];else return toast('Сброс недоступен','error')}else{var ta=document.querySelector('[data-v4-text="'+key+'"]');if(!ta||!ta.value.trim())return toast('Текст не может быть пустым','error');all[key]=ta.value.trim()}await api('/api/staff/notification-templates',{method:'POST',body:{templates:all}});templates=all;toast('Текст сохранён','success')}
 function cleanMedia(){mediaUrls.forEach(function(u){try{URL.revokeObjectURL(u)}catch(e){}});mediaUrls=[]}
 function jobStatus(j){if(j.staff_verified)return['Принято','ready'];if(j.stage==='done')return['Ждёт проверки','review'];if(j.stage==='before_sent')return['Чек-лист / после',''];if(j.stage==='started')return['Фото ДО',''];return['В работе','']}
 async function renderPhotos(force){var main=document.getElementById('main');if(!main||activeTab()!=='photos')return;var st=await ensureState();if(!st.admin)return;if(force||!photoJobs){try{var x=await api('/api/admin/jobs');photoJobs=x.jobs||[]}catch(e){main.innerHTML='<div class="hc-v4-photo-empty">Не удалось загрузить фотоотчёты: '+esc(e.message)+'</div>';return}}main.dataset.hcCatalogPage='photos';var rows=(photoJobs||[]).filter(function(j){if(photoFilter==='review')return j.stage==='done'&&!j.staff_verified;if(photoFilter==='done')return !!j.staff_verified;if(photoFilter==='work')return !j.staff_verified&&j.stage!=='done';return true});main.innerHTML='<div class="hc-v4-photo-page"><div class="hc-v4-photo-head"><h2>Фотоотчёты</h2><span>'+rows.length+' записей</span></div><div class="hc-v4-photo-tabs"><button data-v4-pf="all" class="'+(photoFilter==='all'?'on':'')+'">Все</button><button data-v4-pf="review" class="'+(photoFilter==='review'?'on':'')+'">На проверке</button><button data-v4-pf="work" class="'+(photoFilter==='work'?'on':'')+'">В работе</button><button data-v4-pf="done" class="'+(photoFilter==='done'?'on':'')+'">Приняты</button></div><div id="hcV4PhotoList">'+(rows.length?rows.map(function(j){var s=jobStatus(j),id=esc(j.id||j.reportId||'');return'<button class="hc-v4-photo-card" data-v4-job="'+id+'"><strong>'+esc(j.customer||j.booking_order_number||j.reportId||'Фотоотчёт')+'</strong><p>'+esc(j.address||'Адрес не указан')+'</p><div class="hc-v4-photo-meta"><span>'+esc(j.employeeName||'Сотрудник')+'</span><span class="'+s[1]+'">'+s[0]+'</span></div></button>'}).join(''):'<div class="hc-v4-photo-empty">В этом разделе фотоотчётов пока нет</div>')+'</div></div>'}
 async function openPhoto(id){capture('photos');cleanMedia();var main=document.getElementById('main');if(!main)return;main.innerHTML='<div class="hc-v4-photo-empty">Загрузка фотоотчёта…</div>';try{var x=await api('/api/admin/job?id='+encodeURIComponent(id)),j=x.job||{},m=x.media||{},before=m.before||[],after=m.after||[];main.innerHTML='<div class="hc-v4-photo-detail"><button class="hc-v4-back" id="hcV4PhotoBack">← Фотоотчёты</button><div class="hc-v4-photo-summary"><strong>'+esc(j.customer||j.booking_order_number||j.reportId||j.id)+'</strong><p>'+esc(j.address||'')+(j.employeeName?' · '+esc(j.employeeName):'')+'</p></div><div class="hc-v4-upcoming-head"><h2>Фото ДО</h2><span>'+before.length+'</span></div><div id="hcV4Before" class="hc-v4-photo-grid"></div><div class="hc-v4-upcoming-head"><h2>Фото ПОСЛЕ</h2><span>'+after.length+'</span></div><div id="hcV4After" class="hc-v4-photo-grid"></div></div>';await loadMedia(j.id,'before',before,'hcV4Before');await loadMedia(j.id,'after',after,'hcV4After')}catch(e){main.innerHTML='<button class="hc-v4-back" id="hcV4PhotoBack">← Фотоотчёты</button><div class="hc-v4-photo-empty">'+esc(e.message)+'</div>'}}
 async function loadMedia(job,stage,items,box){var host=document.getElementById(box);if(!host)return;if(!items.length){host.innerHTML='<div class="hc-v4-photo-empty" style="grid-column:1/-1">Нет материалов</div>';return}for(var i=0;i<items.length;i++){var f=items[i],b=document.createElement('button');b.className='hc-v4-photo-thumb';b.innerHTML='…';host.appendChild(b);try{var r=await fetch('/api/admin/media?job='+encodeURIComponent(job)+'&stage='+encodeURIComponent(stage)+'&id='+encodeURIComponent(f.id),{headers:headers()}),blob=await r.blob();if(!r.ok)throw Error('Не удалось загрузить');var url=URL.createObjectURL(blob);mediaUrls.push(url);b.innerHTML=f.type==='video'?'<video src="'+url+'" muted playsinline></video>':'<img src="'+url+'" alt="Фото">';b.dataset.url=url;b.dataset.type=f.type==='video'?'video':'photo';b.onclick=function(){openViewer(this.dataset.url,this.dataset.type)}}catch(e){b.innerHTML='×'}}}
 function openViewer(url,type){var v=document.getElementById('hcV4Viewer');if(!v){v=document.createElement('div');v.id='hcV4Viewer';v.className='hc-v4-media-view';v.innerHTML='<button class="hc-v4-media-close">×</button><div class="hc-v4-media-host"></div>';document.body.appendChild(v);v.querySelector('.hc-v4-media-close').onclick=function(){v.classList.remove('on');v.querySelector('.hc-v4-media-host').innerHTML=''}}var h=v.querySelector('.hc-v4-media-host');h.innerHTML=type==='video'?'<video src="'+url+'" controls autoplay playsinline></video>':'<img src="'+url+'" alt="Фото">';v.classList.add('on')}
 function decorate(){var main=document.getElementById('main');if(!main)return;var p=main.dataset.hcCatalogPage||'';if(p==='overview')decorateOverview(main);if(p==='orders')decorateOrders(main);if(document.querySelector('[data-v3-tab="settings"].on'))injectTemplates();if(activeTab()==='photos')renderPhotos(false)}
 function queue(){if(queued)return;queued=true;requestAnimationFrame(function(){queued=false;decorate()})}
 document.addEventListener('click',function(e){var t=e.target;if(!t||!t.closest)return;
   var q=t.closest('[data-v4-go]');if(q){e.preventDefault();var k=q.dataset.v4Go;if(k==='notify'){if(window.__hcOpenNotifications)window.__hcOpenNotifications();else document.dispatchEvent(new CustomEvent('hc:open-notifications'));}else{capture(activeTab());navTo(k,false)}return}
   var m=t.closest('[data-v4-metric]');if(m){e.preventDefault();var k=m.dataset.v4Metric;if(k==='employees')navTo('employees');else navTo('orders');return}
   var a=t.closest('.hc-v4-attention[data-order],.hc-v4-attention[data-v4-target]');if(a){e.preventDefault();capture(activeTab());if(a.dataset.v4Target){navTo(a.dataset.v4Target,false);return}var number=a.dataset.order||'';if(!navTo('orders',false))return;requestAnimationFrame(function(){requestAnimationFrame(function(){var old=document.querySelector('[data-order="'+CSS.escape(number)+'"]');if(old)old.click();else{var q=document.getElementById('search');if(q){q.value=number;q.dispatchEvent(new Event('input',{bubbles:true}))}}})});return}
   var pf=t.closest('[data-v4-pf]');if(pf){e.preventDefault();photoFilter=pf.dataset.v4Pf;renderPhotos(false);return}
   var job=t.closest('[data-v4-job]');if(job){e.preventDefault();openPhoto(job.dataset.v4Job);return}
   if(t.closest('#hcV4PhotoBack')){e.preventDefault();cleanMedia();renderPhotos(false);restore('photos');return}
   var sv=t.closest('[data-v4-save]');if(sv){e.preventDefault();saveTemplate(sv.dataset.v4Save,false).catch(function(x){toast(x.message,'error')});return}
   var rs=t.closest('[data-v4-reset]');if(rs){e.preventDefault();var key=rs.dataset.v4Reset,ta=document.querySelector('[data-v4-text="'+key+'"]');if(defaults&&defaults[key]&&ta)ta.value=defaults[key];else toast('Для сброса откройте экран заново','info');return}
   var open=t.closest('[data-order],.hc-client-card,[data-employee]');if(open&&!t.closest('#nav'))capture(activeTab());
   var back=t.closest('.back,.hc-client-back,.hc-v3-back');if(back){var tab=activeTab();setTimeout(function(){restore(tab)},20)}
 },false);
 document.addEventListener('input',function(e){var t=e.target;if(t&&activeTab()==='orders'&&(t.matches('.search')||t.matches('input'))){var v=viewState.orders||{};v.q=t.value;viewState.orders=v;save()}},false);
 document.addEventListener('hc:after-render',function(){queue()},false);window.addEventListener('pageshow',queue);document.addEventListener('visibilitychange',function(){if(!document.hidden)queue()});queue();
})();
</script>`;

export function applyStaffCommandV4(app:string):string{
  if(!app||app.includes('hcCommandV4Script'))return app;
  return app.replace('</head>',CSS+'</head>').replace('</body>',JS+'</body>');
}
