import { STAFF_ADMIN_ACCESS_APP } from './staff-admin-access-ui';

const PERF_CSS = String.raw`
<style>
.hc-defect-panel{margin:12px 0;padding:13px;border:1.5px solid #efb1b1;border-radius:17px;background:linear-gradient(180deg,#fff7f7,#fff1f1)}
.hc-defect-panel .hc-defect-title{font-size:15px;font-weight:900;color:#9a3030;display:flex;gap:7px;align-items:center}.hc-defect-panel .hc-defect-help{font-size:11px;line-height:1.45;color:#825c5c;margin:5px 0 10px}.hc-defect-panel textarea{width:100%;min-height:70px;border:1px solid #e8bcbc;border-radius:12px;background:#fff;color:#222;padding:10px;font:inherit;resize:vertical}.hc-defect-upload{display:flex;align-items:center;justify-content:center;min-height:48px;margin-top:9px;border-radius:13px;background:#b83b3b;color:#fff;font-weight:850;cursor:pointer;touch-action:manipulation}.hc-defect-upload input{position:absolute;opacity:0;pointer-events:none;width:1px;height:1px}.hc-defect-status{font-size:11px;color:#7e5050;margin-top:8px;line-height:1.4}.hc-defect-status.ok{color:#8b2828;font-weight:750}.hc-normal-label{font-size:12px;font-weight:850;color:#536274;margin:7px 0 6px}.hc-defect-report{margin:15px 0;padding:13px;border:1.5px solid #e89b9b;border-radius:18px;background:#fff4f4}.hc-defect-report-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px}.hc-defect-report-head strong{font-size:17px;color:#962d2d}.hc-defect-count{padding:4px 8px;border-radius:999px;background:#b83b3b;color:#fff;font-size:10px;font-weight:900}.hc-defect-notes{display:grid;gap:6px;margin:7px 0 10px}.hc-defect-note{padding:8px 9px;border-radius:10px;background:#fff;border:1px solid #efd0d0;color:#6e3d3d;font-size:11px;line-height:1.4}.hc-media-grid{content-visibility:auto;contain-intrinsic-size:210px}.hc-media{touch-action:manipulation}.hc-media img,.hc-media video{content-visibility:auto}.hc-media-skeleton{display:grid;place-items:center;min-height:110px;background:#eef3f8;border-radius:14px;color:#7b8797;font-size:11px}.hc-photo-loading-note{font-size:11px;color:#718095;margin:7px 0}.btn,button,[role="button"]{touch-action:manipulation}
</style>`;

const CURRENT_POLL = "var mo=new MutationObserver(function(){requestAnimationFrame(patch)});mo.observe(document.documentElement,{subtree:true,childList:true});setInterval(patch,1000);setTimeout(hydrate,50);patch();";
const CURRENT_EVENTS = "var hcPatchTimer=0;function hcSchedulePatch(){if(hcPatchTimer)return;requestAnimationFrame(function(){patch()});hcPatchTimer=setTimeout(function(){hcPatchTimer=0;patch()},220)}document.addEventListener('click',hcSchedulePatch,true);document.addEventListener('change',hcSchedulePatch,true);window.addEventListener('pageshow',hcSchedulePatch);document.addEventListener('visibilitychange',function(){if(!document.hidden)hcSchedulePatch()});setTimeout(hydrate,50);hcSchedulePatch();";
const RUNTIME_POLL = "var mo=new MutationObserver(function(){requestAnimationFrame(patch)});mo.observe(document.documentElement,{subtree:true,childList:true});setInterval(patch,1000);patch();";
const RUNTIME_EVENTS = "var rtPatchTimer=0;function rtSchedulePatch(){if(rtPatchTimer)return;requestAnimationFrame(function(){patch()});rtPatchTimer=setTimeout(function(){rtPatchTimer=0;patch()},260)}document.addEventListener('click',rtSchedulePatch,true);document.addEventListener('change',rtSchedulePatch,true);window.addEventListener('pageshow',rtSchedulePatch);document.addEventListener('visibilitychange',function(){if(!document.hidden)rtSchedulePatch()});rtSchedulePatch();";

let optimized = STAFF_ADMIN_ACCESS_APP
  .split(CURRENT_POLL).join(CURRENT_EVENTS)
  .split(RUNTIME_POLL).join(RUNTIME_EVENTS);

// Replace the old sequential media downloader. Report shell renders immediately;
// thumbnails download in a small pool and are cached for the Mini App session.
optimized = optimized.replace(
  /async function hcLoadMedia\(job,stage,items,box,title\)\{[\s\S]*?\}\n\nreportDetail=async function\(id\)/,
  String.raw`function hcMediaCache(){return window.__hcStaffMediaCache||(window.__hcStaffMediaCache=new Map())}
function hcMediaPut(key,value){var c=hcMediaCache();c.set(key,value);while(c.size>60){var first=c.keys().next().value,old=c.get(first);c.delete(first);try{if(old&&old.url)URL.revokeObjectURL(old.url)}catch(e){}}}
async function hcMediaOne(job,stage,f){var key=String(job)+':'+String(stage)+':'+String(f.id),c=hcMediaCache();if(c.has(key))return c.get(key);var r=await fetch('/api/admin/media?job='+encodeURIComponent(job)+'&stage='+encodeURIComponent(stage)+'&id='+encodeURIComponent(f.id),{headers:hcMediaHeaders()}),b=await r.blob();if(!r.ok)throw Error('media');var value={url:URL.createObjectURL(b),type:f.type==='video'?'video':'photo'};hcMediaPut(key,value);return value}
async function hcLoadMedia(job,stage,items,box,title){var host=document.getElementById(box);if(!host)return;if(!items.length){host.innerHTML='<div class="sub">Нет материалов</div>';return}host.innerHTML='<div class="hc-photo-loading-note">Превью загружаются в фоне — экраном уже можно пользоваться</div><div class="hc-media-grid">'+items.map(function(f,i){return '<button class="hc-media" data-mi="'+i+'"><span class="hc-media-skeleton">Фото '+(i+1)+'</span></button>'}).join('')+'</div>';var loaded=new Array(items.length),cursor=0,stopped=false;async function worker(){while(!stopped){var i=cursor++;if(i>=items.length)return;try{var f=items[i],value=await hcMediaOne(job,stage,f);loaded[i]=value;if(!document.body.contains(host)){stopped=true;return}var el=host.querySelector('[data-mi="'+i+'"]');if(!el)continue;el.innerHTML=f.type==='video'?'<video src="'+value.url+'" muted playsinline preload="metadata"></video>':'<img src="'+value.url+'" alt="Фото" loading="lazy" decoding="async">';el.onclick=(function(ix){return function(){var available=loaded.filter(Boolean),target=loaded[ix],pos=available.indexOf(target);hcOpenViewer(available,pos<0?0:pos,title)}})(i)}catch(e){var bad=host.querySelector('[data-mi="'+i+'"]');if(bad)bad.innerHTML='<span class="hc-media-skeleton">Повторить</span>';if(bad)bad.onclick=function(){hcLoadMedia(job,stage,items,box,title)}}}}Promise.all([worker(),worker(),worker()]).catch(function(){})}

reportDetail=async function(id)`
);

// Separate defect photos from ordinary BEFORE photos in manager report.
optimized = optimized.replace(
  /reportDetail=async function\(id\)\{[\s\S]*?\}\n\nfunction hcTaskCard/,
  String.raw`reportDetail=async function(id){try{var x=await api('/api/admin/job?id='+encodeURIComponent(id)),j=x.job||{},m=x.media||{},before=m.before||[],after=m.after||[],defects=before.filter(function(f){return!!f.is_defect}),normal=before.filter(function(f){return!f.is_defect}),verified=!!j.staff_verified,defectNotes=defects.map(function(f,i){return f.defect_note?'<div class="hc-defect-note"><b>Дефект '+(i+1)+':</b> '+H(f.defect_note)+'</div>':''}).join('');M('<button id="pback" class="back">← Фотоотчёты</button><div class="card"><div class="title">'+H(j.reportId||j.booking_order_number||j.id)+'</div><div class="sub">'+H(j.customer||'')+' · '+H(j.address||'')+'</div><div class="meta"><span class="chip">'+H(j.employeeName||'')+'</span><span class="chip '+(verified?'green':j.stage==='done'?'orange':'blue')+'">'+(verified?'Работа принята':j.stage==='done'?'Готов к проверке':'В работе')+'</span>'+(defects.length?'<span class="chip red">⚠️ Дефектов '+defects.length+'</span>':'')+'</div></div>'+(defects.length?'<div class="hc-defect-report"><div class="hc-defect-report-head"><strong>⚠️ Дефекты до уборки</strong><span class="hc-defect-count">'+defects.length+'</span></div><div class="sub">Эти фотографии клинер специально отметил как существующие дефекты. Клиенту отправляются только они.</div><div class="hc-defect-notes">'+defectNotes+'</div><div id="hcDefects"></div></div>':'')+'<div class="section-title"><h2>Обычные фото ДО</h2><span>'+normal.length+'</span></div><div id="hcBefore"></div><div class="section-title"><h2>Фото ПОСЛЕ</h2><span>'+after.length+'</span></div><div id="hcAfter"></div>'+(verified?'<div class="readonly-box" style="margin-top:14px"><b>✅ Работа принята</b>Фотоотчёт зафиксирован. Сотрудник больше не может менять этот заказ.</div>':(j.booking_order_number&&j.stage==='done'?'<div class="sticky-actions"><button id="verify" class="btn green block">Принять работу и закрыть заказ</button></div>':'')));document.getElementById('pback').onclick=function(){go('photos')};if(defects.length)hcLoadMedia(j.id,'before',defects,'hcDefects','ДЕФЕКТЫ ДО УБОРКИ');hcLoadMedia(j.id,'before',normal,'hcBefore','ДО УБОРКИ');hcLoadMedia(j.id,'after',after,'hcAfter','ПОСЛЕ УБОРКИ');var v=document.getElementById('verify');if(v)v.onclick=async function(){try{await api('/api/staff/order/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({order_number:j.booking_order_number,job_id:j.id})});await reloadAdmin();toast('Работа принята, начисления зафиксированы');reportDetail(id)}catch(e){toast(e.message)}}}catch(e){toast(e.message)}};

function hcTaskCard`
);

const DEFECT_SCRIPT = String.raw`
<script>
(function(){
  var defectBusy=false,defectTimer=0;
  function tg(){return window.Telegram&&window.Telegram.WebApp}
  function headers(json){var h={'X-App-Launch-Token':new URLSearchParams(location.search).get('launch')||'','X-Telegram-Init-Data':tg()&&tg().initData||''};if(json)h['content-type']='application/json';return h}
  function message(s){try{var t=tg();if(t&&t.showAlert)return t.showAlert(String(s))}catch(e){}alert(String(s))}
  async function jsonApi(path){var r=await fetch(path,{headers:headers(false)}),x=await r.json().catch(function(){return{}});if(!r.ok||x.ok===false)throw Error(x.error||'Ошибка');return x}
  function orderNumber(up){return String(up&&up.dataset&&up.dataset.order||'').trim()}
  async function refresh(order){var box=document.getElementById('hcDefectStatus');if(!box||!order)return;try{var x=await jsonApi('/api/staff/defects?order_number='+encodeURIComponent(order)),n=(x.defects||[]).length;box.className='hc-defect-status'+(n?' ok':'');box.textContent=n?'Отмечено дефектов: '+n+'. Клиент получит только эти фотографии после отправки Фото ДО.':'Дефекты не отмечены — клиенту обычные фото ДО не отправляются.'}catch(e){box.textContent='Дефекты сохранятся вместе с фото ДО.'}}
  function enhance(){var up=document.getElementById('upload');if(!up||String(up.dataset.stage||'')!=='before'||up.dataset.hcDefectUi)return;up.dataset.hcDefectUi='1';var order=orderNumber(up);var normal=document.createElement('div');normal.className='hc-normal-label';normal.textContent='Обычные фото ДО';up.insertAdjacentElement('beforebegin',normal);var old=document.getElementById('defect');if(old){old.style.display='none'}var panel=document.createElement('div');panel.className='hc-defect-panel';panel.innerHTML='<div class="hc-defect-title">⚠️ Зафиксировать дефект</div><div class="hc-defect-help">Если повреждение было на объекте до уборки — кратко опишите его и прикрепите фото. Только отмеченные здесь фотографии автоматически отправятся клиенту.</div><textarea id="hcDefectNote" placeholder="Например: скол на столешнице у мойки"></textarea><label class="hc-defect-upload">＋ Добавить фото дефекта<input id="hcDefectUpload" type="file" accept="image/*" multiple></label><div id="hcDefectStatus" class="hc-defect-status">Проверяем сохранённые дефекты…</div>';var send=document.getElementById('sendstage');if(send)send.insertAdjacentElement('beforebegin',panel);else up.insertAdjacentElement('afterend',panel);var input=document.getElementById('hcDefectUpload');input.onchange=async function(){var files=[].slice.call(input.files||[]),note=String((document.getElementById('hcDefectNote')||{}).value||'').trim();if(!files.length)return;if(note.length<2){input.value='';return message('Коротко опишите дефект перед добавлением фото.')}if(defectBusy)return;defectBusy=true;input.disabled=true;var status=document.getElementById('hcDefectStatus');try{for(var i=0;i<files.length;i++){status.textContent='Сохраняем дефект '+(i+1)+' из '+files.length+'…';var fd=new FormData();fd.append('stage','before');fd.append('order_number',order);fd.append('client_id','defect-'+Date.now()+'-'+i+'-'+Math.random().toString(36).slice(2));fd.append('is_defect','1');fd.append('defect_note',note);fd.append('media',files[i]);var r=await fetch('/api/media/draft',{method:'POST',headers:Object.assign({},headers(false),{'X-HC-Defect':'1'}),body:fd}),x=await r.json().catch(function(){return{}});if(!r.ok||x.ok===false)throw Error(x.error||'Не удалось сохранить фото дефекта')}document.getElementById('hcDefectNote').value='';input.value='';await refresh(order)}catch(e){message(e.message);status.textContent='Не удалось сохранить один из дефектов. Повторите загрузку.'}finally{defectBusy=false;input.disabled=false}};refresh(order)}
  function schedule(){if(defectTimer)return;requestAnimationFrame(enhance);defectTimer=setTimeout(function(){defectTimer=0;enhance()},260)}
  document.addEventListener('click',schedule,true);document.addEventListener('change',schedule,true);window.addEventListener('pageshow',schedule);document.addEventListener('visibilitychange',function(){if(!document.hidden)schedule()});schedule();
})();
</script>`;

export const STAFF_DEFECTS_PERFORMANCE_APP = optimized
  .replace('</head>', PERF_CSS + '</head>')
  .replace('</body>', DEFECT_SCRIPT + '</body>');
